enum ENVS {
  DEV = 'dev',
  CI_TEST = 'ci_test',
  TEST = 'test',
  STAGING = 'staging',
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

enum STATIC_SCOPE {
  PRIVATE = 'private',
  PUBLIC = 'public',
}

type Scope = STATIC_SCOPE | `space-${number}`

enum HOME_SCOPE {
  ME = 'me',
  FEATURED = 'featured',
  EVERYBODY = 'everybody',
  SPACES = 'spaces',
}

enum NOTIFICATION_ACTION {
  JOB_RUNNING = 'JOB_RUNNING',
  JOB_RUNNABLE = 'JOB_RUNNABLE',
  JOB_DONE = 'JOB_DONE',
  JOB_INITIALIZING = 'JOB_INITIALIZING',
  JOB_FAILED = 'JOB_FAILED',
  JOB_TERMINATED = 'JOB_TERMINATED',
  JOB_OUTPUTS_SYNCED = 'JOB_OUTPUTS_SYNCED',
  FILE_CLOSED = 'FILE_CLOSED',
  DOWNLOAD_FILES_WARNING = 'DOWNLOAD_FILES_WARNING',
  CHALLENGE_RESOURCE_URL_UPDATED = 'CHALLENGE_RESOURCE_URL_UPDATED',
  DATA_PORTAL_CARD_IMAGE_URL_UPDATED = 'DATA_PORTAL_CARD_IMAGE_URL_UPDATED',
  CHALLENGE_CARD_IMAGE_URL_UPDATED = 'CHALLENGE_CARD_IMAGE_URL_UPDATED',
  NODES_REMOVED = 'NODES_REMOVED',
  NODES_COPIED = 'NODES_COPIED',
  NODES_LOCKED = 'NODES_LOCKED',
  NODES_UNLOCKED = 'NODES_UNLOCKED',
  SPACE_ACTIVATED = 'SPACE_ACTIVATED',
  WORKSTATION_SNAPSHOT_COMPLETED = 'WORKSTATION_SNAPSHOT_COMPLETED',
  WORKSTATION_SNAPSHOT_ERROR = 'WORKSTATION_SNAPSHOT_ERROR',
  SPACE_REPORT_ERROR = 'SPACE_REPORT_ERROR',
  SPACE_REPORT_DONE = 'SPACE_REPORT_DONE',
}

enum SEVERITY {
  ERROR = 'ERROR',
  WARN = 'WARN',
  INFO = 'INFO',
}

export { ENVS, STATIC_SCOPE, Scope, HOME_SCOPE, NOTIFICATION_ACTION, SEVERITY }
