export const HOME_DATABASES_FETCH_START = 'HOME_DATABASES_FETCH_START'
export const HOME_DATABASES_FETCH_SUCCESS = 'HOME_DATABASES_FETCH_SUCCESS'
export const HOME_DATABASES_FETCH_FAILURE = 'HOME_DATABASES_FETCH_FAILURE'

export const HOME_DATABASES_FETCH_DETAILS_START = 'HOME_DATABASES_FETCH_DETAILS_START'
export const HOME_DATABASES_FETCH_DETAILS_SUCCESS = 'HOME_DATABASES_FETCH_DETAILS_SUCCESS'
export const HOME_DATABASES_FETCH_DETAILS_FAILURE = 'HOME_DATABASES_FETCH_DETAILS_FAILURE'

export const HOME_DATABASES_TOGGLE_ALL_CHECKBOXES = 'HOME_DATABASES_TOGGLE_ALL_CHECKBOXES'
export const HOME_DATABASES_TOGGLE_CHECKBOX = 'HOME_DATABASES_TOGGLE_CHECKBOX'

export const HOME_DATABASES_EDIT_TAGS_START = 'HOME_DATABASES_EDIT_TAGS_START'
export const HOME_DATABASES_EDIT_TAGS_SUCCESS = 'HOME_DATABASES_EDIT_TAGS_SUCCESS'
export const HOME_DATABASES_EDIT_TAGS_FAILURE = 'HOME_DATABASES_EDIT_TAGS_FAILURE'

export const HOME_DATABASE_CREATE_START = 'HOME_DATABASE_CREATE_START'
export const HOME_DATABASE_CREATE_SUCCESS = 'HOME_DATABASE_CREATE_SUCCESS'
export const HOME_DATABASE_CREATE_FAILURE = 'HOME_DATABASE_CREATE_FAILURE'

export const HOME_DATABASES_SET_FILTER_VALUE = 'HOME_DATABASES_SET_FILTER_VALUE'
export const HOME_DATABASES_RESET_FILTERS = 'HOME_DATABASES_RESET_FILTERS'

export const HOME_DATABASES_SHOW_MODAL = 'HOME_DATABASES_SHOW_MODAL'
export const HOME_DATABASES_HIDE_MODAL = 'HOME_DATABASES_HIDE_MODAL'
export const HOME_DATABASES_RESET_MODALS = 'HOME_DATABASES_RESET_MODALS'

export const HOME_DATABASE_MODAL_ACTION_START = 'HOME_DATABASE_MODAL_ACTION_START'
export const HOME_DATABASE_MODAL_ACTION_SUCCESS = 'HOME_DATABASE_MODAL_ACTION_SUCCESS'
export const HOME_DATABASE_MODAL_ACTION_FAILURE = 'HOME_DATABASE_MODAL_ACTION_FAILURE'

export const HOME_COPY_DATABASE_TO_SPACE_START = 'HOME_COPY_DATABASE_TO_SPACE_START'
export const HOME_COPY_DATABASE_TO_SPACE_SUCCESS = 'HOME_COPY_DATABASE_TO_SPACE_SUCCESS'
export const HOME_COPY_DATABASE_TO_SPACE_FAILURE = 'HOME_COPY_DATABASE_TO_SPACE_FAILURE'

export const HOME_DATABASE_EDIT_INFO_START = 'HOME_DATABASE_EDIT_INFO_START'
export const HOME_DATABASE_EDIT_INFO_SUCCESS = 'HOME_DATABASE_EDIT_INFO_SUCCESS'
export const HOME_DATABASE_EDIT_INFO_FAILURE = 'HOME_DATABASE_EDIT_INFO_FAILURE'

export const HOME_DATABASES_RUN_ACTION_START = 'HOME_DATABASES_RUN_ACTION_START'
export const HOME_DATABASES_RUN_ACTION_SUCCESS = 'HOME_DATABASES_RUN_ACTION_SUCCESS'
export const HOME_DATABASES_RUN_ACTION_FAILURE = 'HOME_DATABASES_RUN_ACTION_FAILURE'
