import { IsBoolean, IsOptional, IsString } from 'class-validator'

/**
 * DTO for job snapshot request body.
 *
 * TODO: Before we expose nodejs-api as an externally accessible endpoint make sure
 *       we also migrate CLI key generation and platform auth code creation to nodejs first.
 */
export class JobSnapshotBodyDTO {
  @IsString()
  key: string // 'key' is used by the CLI to authenticate against the pFDA backend

  @IsString()
  code: string // 'code' is authorization_code generated by platform to authenticate against the workstation

  @IsString()
  name: string

  @IsBoolean()
  @IsOptional()
  terminate: boolean = false // TODO - try if this works as the screenshot says.
}
