import { IsString } from 'class-validator'

/**
 * DTO for job set API key request body.
 *
 */
export class JobSetAPIKeyBodyDTO {
  @IsString()
  code: string // 'code' is authorization_code generated by platform to authenticate against the workstation

  @IsString()
  key: string // 'key' is used by the CLI to authenticate against the pFDA backend
}
