import { IsString } from 'class-validator'

/**
 * DTO for workstation alive check request body.
 */
export class WorkstationAliveBodyDTO {
  @IsString()
  code: string // 'code' is authorization_code generated by platform to authenticate against the workstation
}
