version: "3.2"
services:
  web:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /precision-fda
      - type: volume
        source: gems
        target: /usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.6
    volumes:
      - 'pfda-mysql-volume:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
volumes:
  pfda-mysql-volume:
  gems:
