module Imports
  # Workflow slots constants for CWL presenter specs.
  module WorkflowHelper
    # rubocop:disable Metrics/MethodLength
    def params
      { "slots" => [
        { "uid" => "app-FXKBg3803PFFYJjz11BgJ4b4-1",
          "name" => "app-776-first-step-1",
          "instanceType" => "baseline-4",
          "inputs" => [
            { "name" => "input_file_param_1",
              "class" => "file",
              "parent_slot" => "stage-lnuqrt1wxs0000",
              "stageName" => "app-776-first-step-1",
              "values" => { "id" => nil, "name" => nil },
              "requiredRunInput" => true,
              "optional" => false, "label" => "" },
            { "name" => "input_string_param_1",
              "class" => "string",
              "parent_slot" => "stage-lnuqrt1wxs0000",
              "stageName" => "app-776-first-step-1",
              "values" => { "id" => nil, "name" => nil },
              "requiredRunInput" => true,
              "optional" => false, "label" => "" },
          ],
          "outputs" => [
            { "name" => "output_file_param_1",
              "class" => "file",
              "parent_slot" => "stage-lnuqrt1wxs0000",
              "stageName" => "app-776-first-step-1",
              "values" => { "id" => "stage-ec9qciiclc0000", "name" => "app-776-second-step-1" },
              "requiredRunInput" => false,
              "optional" => false,
              "label" => "" },
            { "name" => "output_string_param_1",
              "class" => "string",
              "parent_slot" => "stage-lnuqrt1wxs0000",
              "stageName" => "app-776-first-step-1",
              "values" => { "id" => "stage-ec9qciiclc0000", "name" => "app-776-second-step-1" },
              "requiredRunInput" => false, "optional" => false, "label" => "" },
          ],
          "slotId" => "stage-lnuqrt1wxs0000",
          "nextSlot" => "stage-ec9qciiclc0000",
          "stageIndex" => 0 },
        { "uid" => "app-FXKBjg807jkfZKYq126yx61f-1",
          "name" => "app-776-second-step-1",
          "instanceType" => "baseline-4",
          "inputs" => [
            { "name" => "input_file_param_1",
              "class" => "file",
              "parent_slot" => "stage-ec9qciiclc0000",
              "stageName" => "app-776-second-step-1",
              "values" => { "id" => "stage-lnuqrt1wxs0000", "name" => "output_file_param_1" },
              "requiredRunInput" => false,
              "optional" => false,
              "label" => "" },
            { "name" => "input_string_param_1",
              "class" => "string",
              "parent_slot" => "stage-ec9qciiclc0000",
              "stageName" => "app-776-second-step-1",
              "values" => { "id" => "stage-lnuqrt1wxs0000", "name" => "output_string_param_1" },
              "requiredRunInput" => false,
              "optional" => false,
              "label" => "" },
          ],
          "outputs" => [
            { "name" => "output_file_param_1",
              "class" => "file",
              "parent_slot" => "stage-ec9qciiclc0000",
              "stageName" => "app-776-second-step-1",
              "values" => { "id" => nil, "name" => nil },
              "requiredRunInput" => false,
              "optional" => false,
              "label" => "" },
            { "name" => "output_string_param_1",
              "class" => "string",
              "parent_slot" => "stage-ec9qciiclc0000",
              "stageName" => "app-776-second-step-1",
              "values" => { "id" => nil, "name" => nil },
              "requiredRunInput" => false,
              "optional" => false,
              "label" => "" },
          ],
          "slotId" => "stage-ec9qciiclc0000",
          "prevSlot" => "stage-lnuqrt1wxs0000",
          "stageIndex" => 1 },
      ],
        "workflow_name" => "workflow-776-4",
        "readme" => "",
        "workflow_title" => "workflow-776-4",
        "is_new" => true }
    end
    # rubocop:enable Metrics/MethodLength
  end
end
