#!/usr/bin/env python3
# pfda_db_cluster_manager 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/

import os
import dxpy
import json
import base64
from Cryptodome.Cipher import AES
from Cryptodome.Protocol.KDF import scrypt
from Cryptodome.Random import get_random_bytes
import postgres_manager
import mysql_manager


def get_dbcluster_info(dbcluster_id):
    info = dxpy.api.dbcluster_describe(dbcluster_id)
    return info['endpoint'], info['engine']

def derive_key(encyption_password, salt):
    key = scrypt(encyption_password.encode(), salt, 32, N=2**14, r=8, p=1)
    return key

def decrypt(encrypted_data, encryption_password):
    salt = base64.b64decode(encrypted_data['salt'])
    iv = base64.b64decode(encrypted_data['iv'])
    ciphertext = base64.b64decode(encrypted_data['ciphertext'])
    tag = base64.b64decode(encrypted_data['tag'])

    key = derive_key(encryption_password, salt)

    cipher = AES.new(key, AES.MODE_GCM, nonce=iv)

    decrypted_data = cipher.decrypt_and_verify(ciphertext, tag)
    return json.loads(decrypted_data.decode())

def get_encryption_password():
    file = open("encryption_password", "r")
    psw = file.read().rstrip('\n')
    file.close()
    return psw
        
@dxpy.entry_point('main')
def main(encrypted_input_json):    
    encryption_password = get_encryption_password()
    decrypted_json = decrypt(encrypted_input_json, encryption_password)

    db_cluster_id = decrypted_json['db_cluster_id']
    db_cluster_admin_username = decrypted_json['db_cluster_admin_username']
    db_cluster_admin_password = decrypted_json['db_cluster_admin_password']
    users_mapping = decrypted_json['users_mapping']

    db_cluster_url, engine = get_dbcluster_info(db_cluster_id)
    print(f"DBcluster info obtained: {db_cluster_url}, {engine}")

    if engine == 'aurora-postgresql':
        manager = postgres_manager.PostgresManager()
    elif engine == 'aurora-mysql':
        manager = mysql_manager.MySQLManager()
    else:
        raise Exception(f"Engine {engine} not supported.")

    conn = manager.connect(db_cluster_url, db_cluster_admin_username, db_cluster_admin_password)
    if not conn:
        raise Exception("Failed to connect to the database.")
    
    try:
        with conn:
            with conn.cursor() as cur:
                print("Connected to the DBcluster.")

                if manager.is_first_run(cur):
                    print("First run of the synchronization app, preparing db..")
                    manager.prepare_db(cur)

                existing_users = manager.get_existing_users(cur)
                print(f"Fetched existing users: {existing_users}")

                for user in users_mapping:
                    username = user['username']
                    if manager.user_exists(cur, username):
                        manager.update_user(cur, user)
                        print(f"User '{username}' updated.")
                    else:
                        manager.add_user(cur, user)
                        print(f"User '{username}' added.")

                usernames = set(user['username'] for user in users_mapping)
                users_to_remove = existing_users - usernames
                print(f"Users to be removed: {users_to_remove}")

                for username in users_to_remove:
                    manager.remove_user(cur, username)
                    print(f"User '{username}' removed.")
            conn.commit()

    except Exception as e:
        raise Exception(f"An error occurred while managing users:\n {e}")

    finally:
        if conn:
            conn.close()

    print("Synchronization completed!")
    output = {}
    return output

dxpy.run()
