import { NOTIFICATION_ACTION } from '../home/types'

export const EXECUTION_LIST_QUERY_KEY = ['jobs'] as const

export const EXECUTION_LIST_NOTIFICATION_ACTIONS: NOTIFICATION_ACTION[] = [
  NOTIFICATION_ACTION.JOB_RUNNABLE,
  NOTIFICATION_ACTION.JOB_RUNNING,
  NOTIFICATION_ACTION.JOB_DONE,
  NOTIFICATION_ACTION.JOB_FAILED,
  NOTIFICATION_ACTION.JOB_OUTPUTS_SYNCED,
]
