import { http, HttpResponse } from 'msw'
import { FetchExecutionsQuery } from './executions.api'

const workflowExecution = {
  id: 111,
  uid: 'workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1',
  name: 'ngs-pipeline',
  title: 'NGS Pipeline',
  added_by: 'Zarlik Vexor',
  created_at: '01/29/2024',
  created_at_date_time: '2024-01-29 12:37:54 UTC',
  launched_by: 'Zarlik Vexor',
  launched_on: '2024-01-29 13:03:26 UTC',
  app_title: '',
  location: 'Private',
  revision: 1,
  readme: '',
  workflow_series_id: 1,
  version: '0',
  scope: 'private',
  featured: false,
  active: true,
  links: {
    show: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1',
    user: '/users/zvexor',
    attach_to: '/api/attach_to_notes',
    publish: '/publish?id=workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1',
    copy: '/api/workflows/copy',
    run_workflow: '/api/run_workflow',
    batch_run_workflow: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1/batch_workflow',
    edit: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1/edit',
    fork: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1/fork',
    cwl_export: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1/cwl_export',
    wdl_export: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1/wdl_export',
    set_tags: '/api/set_tags',
    set_tags_target: 'workflow-series-1',
    delete: '/api/workflows/delete',
    feature: '/api/workflows/feature',
  },
  jobs: [
    {
      id: 3333,
      uid: 'job-Gfqp47807byG36jBVYbg330G-1',
      dxid: 'job-Gfqp47807byG36jBVYbg330G',
      state: 'done',
      name: 'pheno-predictor',
      app_title: 'PhenoPredictor',
      app_uid: 'app-GfYzyJ80XKxYfYP22Z77j2Z5-1',
      app_revision: 1,
      app_active: true,
      workflow_title: 'ngs-pipeline',
      workflow_uid: 'workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1',
      platform_tags: null,
      workstation_api_version: null,
      run_input_data: [
        {
          name: 'sfdf',
          class: 'string',
          label: 'sdf',
          value: 'sdfsdf',
        },
      ],
      run_output_data: [],
      run_data_updates: {
        run_instance_type: 'baseline-8',
        run_inputs: {
          sfdf: 'sdfsdf',
        },
      },
      instance_type: 'baseline-8',
      duration: 'N/A',
      duration_in_seconds: 0,
      energy_consumption: 'N/A',
      failure_reason: '',
      failure_message: '',
      created_at: '01/29/2024',
      created_at_date_time: '2024-01-29 13:03:26 UTC',
      scope: 'private',
      location: 'Private',
      launched_by: 'Zarlik Vexor',
      launched_by_dxuser: 'zvexor',
      launched_on: '2024-01-29 13:03:26 UTC',
      featured: false,
      links: {
        show: '/jobs/job-Gfqp47807byG36jBVYbg330G-1',
        user: '/users/zvexor',
        workflow: '/workflows/workflow-Gfqkj8Q07by7JbB4xVqFQQj1-1',
        log: '/jobs/job-Gfqp47807byG36jBVYbg330G-1/log',
        track: '/track?id=job-Gfqp47807byG36jBVYbg330G-1',
        attach_to: '/api/attach_to_notes',
        copy: '/api/jobs/copy',
        terminate: '/api/jobs/terminate',
        feature: '/api/jobs/feature',
      },
      entity_type: 'regular',
      logged_dxuser: 'zvexor',
      tags: [],
      properties: {},
    },
  ],
  logged_dxuser: 'zvexor',
  tags: [],
  job_count: 1,
  properties: {},
}

export const executionsMocks = [
  http.get('/api/jobs*', () =>
    HttpResponse.json<FetchExecutionsQuery>(
      {
        jobs: [
          workflowExecution,
          {
            id: 22745,
            uid: 'job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
            dxid: 'job-GfQZzB80jy7qJzbk7XQ7g0XY',
            state: 'failed',
            name: 'blast',
            app_title: 'BLAST (Basic Local Alignment Search Tool) ',
            app_uid: 'app-GfQZz980fpQvgVFgJ7bF8b69-287',
            app_revision: 287,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/12/2024',
            created_at_date_time: '2024-01-12 12:41:46 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-12 12:41:46 -02',
            featured: false,
            links: {
              show: '/jobs/job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-GfQZzB80jy7qJzbk7XQ7g0XY-1/log',
              track: '/track?id=job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22745,
            uid: 'job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
            dxid: 'job-GfQZzB80jy7qJzbk7XQ7g0XY',
            state: 'running',
            name: 'bowtie_tophat',
            app_title: 'Bowtie/Tophat ',
            app_uid: 'app-GfQZz980fpQvgVFgJ7bF8b69-287',
            app_revision: 287,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/12/2024',
            created_at_date_time: '2024-01-12 12:41:46 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-12 12:41:46 -02',
            featured: false,
            links: {
              show: '/jobs/job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-GfQZzB80jy7qJzbk7XQ7g0XY-1/log',
              track: '/track?id=job-GfQZzB80jy7qJzbk7XQ7g0XY-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22732,
            uid: 'job-GfQQPb80jy7bj4QXzb4234qX-1',
            dxid: 'job-GfQQPb80jy7bj4QXzb4234qX',
            state: 'runnable',
            name: 'filter_quality',
            app_title: 'Filter Quality',
            app_uid: 'app-GfQQPZ00GkZXYYV2kVkjjvGg-286',
            app_revision: 286,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/12/2024',
            created_at_date_time: '2024-01-12 07:35:17 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-12 07:35:17 -02',
            featured: false,
            links: {
              show: '/jobs/job-GfQQPb80jy7bj4QXzb4234qX-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-GfQQPb80jy7bj4QXzb4234qX-1/log',
              track: '/track?id=job-GfQQPb80jy7bj4QXzb4234qX-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22790,
            uid: 'job-HaPq3300jy7kYX1XV07Jj55K-1',
            dxid: 'job-HaPq3300jy7kYX1XV07Jj55K',
            state: 'done',
            name: 'scoring_matrix_calculation',
            app_title: 'Scoring Matrix Calculation',
            app_uid: 'app-HaPq3200kQ2z6KKYVGVFKZvQ-285',
            app_revision: 285,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/11/2024',
            created_at_date_time: '2024-01-11 07:14:53 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-11 07:14:53 -02',
            featured: false,
            links: {
              show: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1/log',
              track: '/track?id=job-HaPq3300jy7kYX1XV07Jj55K-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22720,
            uid: 'job-GfPq3300jy7kYX1XV07Jj55K-1',
            dxid: 'job-GfPq3300jy7kYX1XV07Jj55K',
            state: 'terminated',
            name: 'sequence_alignment',
            app_title: 'Sequence Alignment',
            app_uid: 'app-GfPq3200kQ2z6KKYVGVFKZvQ-285',
            app_revision: 285,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/11/2024',
            created_at_date_time: '2024-01-11 07:14:53 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-11 07:14:53 -02',
            featured: false,
            links: {
              show: '/jobs/job-GfPq3300jy7kYX1XV07Jj55K-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-GfPq3300jy7kYX1XV07Jj55K-1/log',
              track: '/track?id=job-GfPq3300jy7kYX1XV07Jj55K-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22800,
            uid: 'job-HaPq3300jy7kYX1XV07Jj55K-1',
            dxid: 'job-HaPq3300jy7kYX1XV07Jj55K',
            state: 'terminating',
            name: 'scoring_matrix_calculation',
            app_title: 'Scoring Matrix Calculation',
            app_uid: 'app-HaPq3200kQ2z6KKYVGVFKZvQ-285',
            app_revision: 285,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/11/2024',
            created_at_date_time: '2024-01-11 07:14:53 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-11 07:14:53 -02',
            featured: false,
            links: {
              show: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1/log',
              track: '/track?id=job-HaPq3300jy7kYX1XV07Jj55K-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
          {
            id: 22900,
            uid: 'job-KaPq3300jy7kYX1XV07Jj55K-1',
            dxid: 'job-KaPq3300jy7kYX1XV07Jj55K',
            state: 'idle',
            name: 'scoring_matrix_calculation',
            app_title: 'Scoring Matrix Calculation',
            app_uid: 'app-HaPq3200kQ2z6KKYVGVFKZvQ-285',
            app_revision: 285,
            app_active: true,
            workflow_title: 'N/A',
            workflow_uid: 'N/A',
            platform_tags: null,
            workstation_api_version: null,
            run_input_data: [],
            run_output_data: [],
            run_data_updates: {
              output_folder_path: '',
              run_instance_type: 'baseline-8',
              run_inputs: {},
              run_outputs: null,
            },
            instance_type: 'baseline-8',
            duration: 'N/A',
            duration_in_seconds: 0,
            energy_consumption: '$0.0',
            failure_reason: '',
            failure_message: '',
            created_at: '01/11/2024',
            created_at_date_time: '2024-01-11 07:14:53 -02',
            scope: 'public',
            location: 'Public',
            launched_by: 'Zarlik Vexor',
            launched_by_dxuser: 'zvexor',
            launched_on: '2024-01-11 07:14:53 -02',
            featured: false,
            links: {
              show: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1',
              user: '/users/zvexor',
              workflow: 'N/A',
              log: '/jobs/job-HaPq3300jy7kYX1XV07Jj55K-1/log',
              track: '/track?id=job-HaPq3300jy7kYX1XV07Jj55K-1',
              attach_to: '/api/attach_to_notes',
              copy: '/api/jobs/copy',
              feature: '/api/jobs/feature',
            },
            entity_type: 'regular',
            logged_dxuser: 'randall.ebert',
            tags: [],
            properties: {},
          },
        ],
      },
      { status: 200 },
    ),
  ),
]
