export const CHALLENGES_FETCH_START   = 'CHALLENGES_FETCH_START'
export const CHALLENGES_FETCH_SUCCESS = 'CHALLENGES_FETCH_SUCCESS'
export const CHALLENGES_FETCH_FAILURE = 'CHALLENGES_FETCH_FAILURE'

export const CHALLENGES_YEAR_LIST_FETCH_START = 'CHALLENGES_YEAR_LIST_FETCH_START'
export const CHALLENGES_YEAR_LIST_FETCH_SUCCESS = 'CHALLENGES_YEAR_LIST_FETCH_SUCCESS'
export const CHALLENGES_YEAR_LIST_FETCH_FAILURE = 'CHALLENGES_YEAR_LIST_FETCH_FAILURE'

export const CHALLENGE_FETCH_START    = 'CHALLENGE_FETCH_START'
export const CHALLENGE_FETCH_SUCCESS  = 'CHALLENGE_FETCH_SUCCESS'
export const CHALLENGE_FETCH_FAILURE  = 'CHALLENGE_FETCH_FAILURE'

export const CHALLENGES_SET_PAGE = 'CHALLENGES_SET_PAGE'
export const CHALLENGES_SET_YEAR = 'CHALLENGES_SET_YEAR'
export const CHALLENGES_SET_TIME_STATUS = 'CHALLENGES_SET_TIME_STATUS'
export const CHALLENGES_LIST_RESET_FILTERS = 'CHALLENGES_LIST_RESET_FILTERS'

export const PROPOSE_CHALLENGE_FETCH_START = 'PROPOSE_CHALLENGE_FETCH_START'
export const PROPOSE_CHALLENGE_FETCH_SUCCESS = 'PROPOSE_CHALLENGE_FETCH_SUCCESS'
export const PROPOSE_CHALLENGE_FETCH_FAILURE = 'PROPOSE_CHALLENGE_FETCH_FAILURE'
export const PROPOSE_CHALLENGE_FORM_RESET = 'PROPOSE_CHALLENGE_FORM_RESET'
