export const SUBMISSIONS_FETCH_START   = 'SUBMISSIONS_FETCH_START'
export const SUBMISSIONS_FETCH_SUCCESS = 'SUBMISSIONS_FETCH_SUCCESS'
export const SUBMISSIONS_FETCH_FAILURE = 'SUBMISSIONS_FETCH_FAILURE'
export const SUBMISSIONS_FETCH_ACTIONS = {
  start: SUBMISSIONS_FETCH_START,
  success: SUBMISSIONS_FETCH_SUCCESS,
  failure: SUBMISSIONS_FETCH_FAILURE,
}

export const MY_ENTRIES_FETCH_START   = 'MY_ENTRIES_FETCH_START'
export const MY_ENTRIES_FETCH_SUCCESS = 'MY_ENTRIES_FETCH_SUCCESS'
export const MY_ENTRIES_FETCH_FAILURE = 'MY_ENTRIES_FETCH_FAILURE'
export const MY_ENTRIES_FETCH_ACTIONS = {
  start: MY_ENTRIES_FETCH_START,
  success: MY_ENTRIES_FETCH_SUCCESS,
  failure: MY_ENTRIES_FETCH_FAILURE,
}
