import { Popover } from '@base-ui/react/popover'
import type React from 'react'
import { useEffect, useEffectEvent, useRef } from 'react'
import { Button } from '@/components/Button'
import { ModalHeaderTop, ModalNext } from '../../modal/ModalNext'

interface AccountEmailCredentialsModalProps {
  credentialsError: string | null
  isSavingEmail: boolean
  isShown: boolean
  newEmail: string
  onEditNewEmail: () => void
  onClose: () => void
  onOtpChange: (value: string) => void
  onPasswordChange: (value: string) => void
  onSubmit: () => Promise<void>
  otp: string
  password: string
}

export function AccountEmailCredentialsModal({
  credentialsError,
  isSavingEmail,
  isShown,
  newEmail,
  onEditNewEmail,
  onClose,
  onOtpChange,
  onPasswordChange,
  onSubmit,
  otp,
  password,
}: AccountEmailCredentialsModalProps): React.ReactElement {
  const fieldLabelClassName = 'text-sm font-medium text-(--c-text-600)'
  const fieldInputClassName =
    'w-full max-w-[420px] rounded-md border border-(--c-layout-border) bg-background px-3 py-2.5 text-sm text-(--c-text-700) transition-[border-color,box-shadow] hover:border-(--c-text-400) focus:border-(--primary-500) focus:outline-none focus:shadow-[0_0_0_2px_var(--primary-100)] disabled:cursor-not-allowed disabled:opacity-60'
  const fieldInputErrorClassName = 'border-destructive hover:border-destructive focus:border-destructive'
  const alertRef = useRef<HTMLDivElement>(null)

  const scrollErrorAlertIntoView = useEffectEvent(() => {
    alertRef.current?.scrollIntoView({ block: 'nearest', behavior: 'smooth' })
  })

  useEffect(() => {
    if (credentialsError) {
      scrollErrorAlertIntoView()
    }
  }, [credentialsError])

  return (
    <ModalNext id="account-email-credentials-modal" isShown={isShown} hide={onClose} variant="small">
      <ModalHeaderTop headerText="Confirm Email Change" hide={onClose} disableClose={isSavingEmail} />
      <form
        onSubmit={e => {
          e.preventDefault()
          void onSubmit()
        }}
      >
        <div className="flex flex-col gap-4 p-6">
          <div className="flex flex-col gap-1 rounded-md border border-(--c-layout-border) bg-muted/40 px-3 py-2.5">
            <div className="flex items-start justify-between gap-2">
              <span className="text-xs font-medium text-(--c-text-500)">New email address</span>
              <button
                type="button"
                className="shrink-0 cursor-pointer border-0 bg-transparent p-0 text-xs font-medium text-(--primary-500) underline disabled:cursor-not-allowed disabled:opacity-50"
                onClick={onEditNewEmail}
                disabled={isSavingEmail}
              >
                Edit
              </button>
            </div>
            <span className="break-all text-sm font-medium text-(--c-text-700)">{newEmail}</span>
          </div>

          <p className="m-0 text-sm leading-relaxed text-(--c-text-500)">
            Enter your password and one-time password to confirm this change.{' '}
            <Popover.Root>
              <Popover.Trigger
                type="button"
                className="inline cursor-pointer border-0 bg-transparent p-0 align-baseline text-sm font-inherit text-(--primary-500) underline"
              >
                How do I do this?
              </Popover.Trigger>
              <Popover.Portal>
                <Popover.Positioner sideOffset={8} side="bottom" align="start" className="z-550">
                  <Popover.Popup className="flex max-w-[320px] flex-col gap-3 rounded-lg border border-(--c-layout-border) bg-background px-4 py-3.5 shadow-[0_8px_24px_rgba(0,0,0,0.15)]">
                    <p className="m-0 text-sm font-semibold text-(--c-text-700)">Two-Factor Authentication</p>
                    <p className="m-0 text-sm leading-[1.4] text-(--c-text-500)">
                      This account is set up to require two-factor authentication at login. This is an optional feature that
                      requires a verification code in addition to a password. Typically, the code is generated by the Google
                      Authenticator app on a mobile device.
                    </p>
                    <p className="m-0 text-sm leading-[1.4] text-(--c-text-500)">
                      Please do not reuse the same code. Instead, wait briefly to enter a newly generated code.
                    </p>
                    <p className="m-0 text-sm leading-[1.4] text-(--c-text-500)">
                      If you have trouble retrieving your verification code, or get locked out of your account accidentally,
                      contact <a href="mailto:precisionfda@fda.hhs.gov" className="text-(--primary-500)">Support</a>.
                    </p>
                  </Popover.Popup>
                </Popover.Positioner>
              </Popover.Portal>
            </Popover.Root>
          </p>

          <div className="flex flex-col gap-2">
            <label className={fieldLabelClassName} htmlFor="account-email-password">
              Password
            </label>
            <input
              id="account-email-password"
              type="password"
              autoComplete="current-password"
              aria-invalid={credentialsError ? true : undefined}
              className={`${fieldInputClassName} ${credentialsError ? fieldInputErrorClassName : ''}`}
              value={password}
              onChange={e => onPasswordChange(e.currentTarget.value)}
              disabled={isSavingEmail}
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className={fieldLabelClassName} htmlFor="account-email-otp">
              One-time password
            </label>
            <input
              id="account-email-otp"
              type="text"
              inputMode="numeric"
              autoComplete="one-time-code"
              aria-invalid={credentialsError ? true : undefined}
              className={`${fieldInputClassName} ${credentialsError ? fieldInputErrorClassName : ''}`}
              value={otp}
              onChange={e => onOtpChange(e.currentTarget.value)}
              disabled={isSavingEmail}
            />
          </div>

          {credentialsError && (
            <div
              ref={alertRef}
              role="alert"
              className="rounded-md border border-destructive/50 bg-destructive/10 px-3 py-2.5"
            >
              <p className="m-0 text-sm font-semibold text-destructive">Could not save your email</p>
            </div>
          )}
        </div>

        <div className="flex justify-end gap-3 border-t border-(--c-layout-border) px-6 pt-4 pb-6">
          <Button type="button" onClick={onClose} disabled={isSavingEmail}>
            Cancel
          </Button>
          <Button type="submit" data-variant="primary" disabled={isSavingEmail}>
            {isSavingEmail ? 'Saving...' : 'Save'}
          </Button>
        </div>
      </form>
    </ModalNext>
  )
}
