# NOTE(samuel) - docs - volumes have to always be in leaf docker compose files
volumes:
  bundler-deps-cache-ruby:
  db-pfda-mysql-volume:
  vite-cache-client:
  pnpm-store-cache-client:
  pnpm-store-cache-nodejs-api:
  pnpm-store-cache-nodejs-worker:
  pnpm-deps-cache-client:
  pnpm-deps-cache-nodejs-api:
  pnpm-deps-cache-nodejs-worker:
  pnpm-deps-cache-docs:

services:
  web:
    platform: linux/arm64
    depends_on:
      - db
      - redis
    extends:
      file: ./base.services.yml
      service: web
    build:
      context: ../packages/rails
      dockerfile: ./docker/images/isolation.arm64v8.Dockerfile
    environment:
      - ARM64V8_DEVELOPMENT_PATCH=1
      - RAILS_ENV=development
      - SKIP_RUBY_DEPS_SETUP=${SKIP_RUBY_DEPS_SETUP}
      - SKIP_DB_SETUP=${SKIP_DB_SETUP}
    volumes:
      - type: bind
        source: ../packages/rails
        target: /precision-fda
      - type: volume
        source: bundler-deps-cache-ruby
        target: /usr/local/bundle
      - ../cert.pem:/cert.pem
      - ../key.pem:/key.pem
  frontend:
    extends:
      file: ./base.services.yml
      service: frontend
    build:
      context: ../packages/client
      dockerfile: ./docker/images/isolation.arm64v8.dev.Dockerfile
    environment:
      - SKIP_FRONTEND_DEPS_SETUP=${SKIP_FRONTEND_DEPS_SETUP}
    volumes:
      - type: volume
        source: vite-cache-client
        target: /precision-fda/node_modules/.vite/
      - type: bind
        source: ../packages/client/src
        target: /precision-fda/src
      - pnpm-store-cache-client:/root/.local/share/pnpm/store
      - pnpm-deps-cache-client:/precision-fda/node_modules
  docs:
    extends:
      file: ./base.services.yml
      service: docs
    build:
      context: ../packages/docs
      dockerfile: ./docker/images/isolation.arm64v8.dev.Dockerfile
    volumes:
      - type: bind
        source: ../packages/docs
        target: /app
      - pnpm-deps-cache-docs:/app/node_modules
  nodejs-api:
    extends:
      file: ./base.services.yml
      service: nodejs-api
    build:
      context: ../packages/server
      dockerfile: ./docker/images/node.isolated-dev.Dockerfile
    command: ["pnpm", "run", "start:dev:api"]
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - NODE_DATABASE_NAME=precision-fda
      - NODE_DATABASE_URL=mysql://root:password@db:3306/precision-fda
      - SKIP_NODEJS_DEPS_SETUP=${SKIP_NODEJS_DEPS_SETUP}
      - SKIP_NODEJS_DB_WAITING=${SKIP_NODEJS_DB_WAITING}
      - NODE_DEV_WATCH=${NODE_DEV_WATCH:-1}
    volumes:
      - type: bind
        source: ../packages/server
        target: /app
      - pnpm-store-cache-nodejs-api:/root/.local/share/pnpm/store
      - pnpm-deps-cache-nodejs-api:/app/node_modules

  nodejs-worker:
    depends_on:
      - db
      - redis
    extends:
      file: ./base.services.yml
      service: nodejs-worker
    build:
      context: ../packages/server
      dockerfile: ./docker/images/node.isolated-dev.Dockerfile
    command: ["pnpm", "run", "start:dev:worker"]
    environment:
      - NODE_ENV=development
      - NODE_DATABASE_NAME=precision-fda
      - NODE_DATABASE_URL=mysql://root:password@db:3306/precision-fda
      - SKIP_NODEJS_DEPS_SETUP=${SKIP_NODEJS_DEPS_SETUP}
      - SKIP_NODEJS_DB_WAITING=${SKIP_NODEJS_DB_WAITING}
      - NODE_DEV_WATCH=${NODE_DEV_WATCH:-1}
    volumes:
      - type: bind
        source: ../packages/server
        target: /app
      - pnpm-store-cache-nodejs-worker:/root/.local/share/pnpm/store
      - pnpm-deps-cache-nodejs-worker:/app/node_modules
  nodejs-admin-platform-client:
    extends:
      file: ./base.services.yml
      service: nodejs-admin-platform-client
    build:
      context: ../packages/server
      dockerfile: ./docker/images/node.isolated-dev.Dockerfile
    command: ["pnpm", "run", "start:dev:admin-platform-client"]
    environment:
      - NODE_ENV=development
      - SKIP_NODEJS_DB_WAITING=1
      - NODE_DEV_WATCH=${NODE_DEV_WATCH:-1}
    volumes:
      - type: bind
        source: ../packages/server
        target: /app
  db:
    platform: linux/arm64
    extends:
      file: ./base.services.yml
      service: db
    volumes:
      - db-pfda-mysql-volume:/var/lib/mysql
  redis:
    extends:
      file: ./base.services.yml
      service: redis
  nginx:
    extends:
      file: ./base.services.yml
      service: nginx
