version: '3.7'

# ! Write a documentation note
# NOTE(samuel): docker volumes cannot be defined in abstract files
volumes:
  bundler-deps-cache-ruby:
  db-pfda-mysql-volume:
  webpack-cache-client:

services:
  web:
    extends:
      file: ./base.services.yml
      service: web
    build:
      context: ../
      dockerfile: docker/images/isolation.arm64v8.Dockerfile
    environment:
      - RAILS_ENV=ui_test
    volumes:
      - type: volume
        source: bundler-deps-cache-ruby
        target: /usr/local/bundle
      - db-pfda-mysql-volume:/var/lib/mysql

  frontend:
    extends:
      file: ./base.services.yml
      service: frontend
    build:
      context: ../client
      dockerfile: ./docker/images/isolation.arm64v8.Dockerfile
    volumes:
      - type: volume
        source: webpack-cache-client
        target: /precision-fda/.build_cache/
  nodejs-api:
    extends:
      file: ./base.services.yml
      service: nodejs-api
  nodejs-worker:
    extends:
      file: ./base.services.yml
      service: nodejs-worker
  db:
    extends:
      file: ./base.services.yml
      service: db_emulated
    volumes:
      - db-pfda-mysql-volume:/var/lib/mysql
  redis:
    extends:
      file: ./base.services.yml
      service: redis
  sidekiq:
    extends:
      file: ./base.services.yml
      service: sidekiq
    build:
      context: ../
      dockerfile: docker/images/isolation.arm64v8.Dockerfile
    environment:
      - RAILS_ENV=ui_test
    volumes:
      - type: volume
        source: bundler-deps-cache-ruby
        target: /usr/local/bundle
