services:
  base_ruby:
    platform: linux/x86_64
    env_file: ../packages/rails/.env
    build:
      context: ../packages/rails
      dockerfile: ./docker/images/isolation.Dockerfile
      args:
        - RUBY_IMAGE_TAG=3.2.2
        - COFFEE_MAJOR_NODE_VERSION=19
    environment:
      - BUNDLER_VERSION=2.4.10
      - LOG_REQUESTS=1
      - NO_FIPS=1
      - REDIS_WORKER_URL=redis://redis:6379/0
  base_nodejs:
    build:
      context: ../packages/server
      dockerfile: ./docker/images/node.isolated-qa.Dockerfile
      args:
        - NODEJS_IMAGE_TAG=20.12.2-slim
    environment:
      - NODEJS_DB_POLLING_INTERVAL=${NODEJS_DB_POLLING_INTERVAL:-5}
      - NODE_REDIS_URL=redis://redis:6379/0
      - NODE_ADMIN_PLATFORM_CLIENT_URL=http://nodejs-admin-platform-client:3002

  web:
    extends:
      service: base_ruby
    volumes:
      - type: bind
        source: ../packages/rails
        target: /precision-fda
      - ../cert.pem:/cert.pem
      - ../key.pem:/key.pem
    working_dir: /precision-fda
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ./docker/entrypoint/isolation.docker-entrypoint.sh

  frontend:
    build:
      context: ../packages/client
      dockerfile: ./docker/images/isolation.Dockerfile
      args:
        - FRONTEND_IMAGE_TAG=20.12.2-slim
    volumes:
      - type: bind
        source: ../packages/rails/app/assets/packs
        target: /precision-fda/dist
    working_dir: /precision-fda
    command: pnpm run watch:docker
  # TODO(samuel) setup correct NODE_ENV here
  nodejs-api:
    environment:
      - NODE_PATH_CERT=/keys/cert.pem
      - NODE_PATH_KEY_CERT=/keys/key.pem
    extends:
      service: base_nodejs
    command: ['make', 'run-dist']
    volumes:
      - ../cert.pem:/keys/cert.pem
      - ../key.pem:/keys/key.pem
    ports:
      - 3001:3001
  nodejs-worker:
    extends:
      service: base_nodejs
    command: ['make', 'run-worker-dist']
  nodejs-admin-platform-client:
    extends:
      service: base_nodejs
    command: [ 'make', 'run-admin-platform-client-dist' ]
    ports:
      - 3002:3002
  sidekiq:
    extends:
      service: base_ruby
    volumes:
      - type: bind
        source: ../packages/rails
        target: /precision-fda
    entrypoint: ./docker/entrypoint/sidekiq.entrypoint.sh
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 32800:3306

  redis:
    image: redis:6.2.11
    ports:
      - 6379:6379
