#!/bin/bash

if [ "$#" -le 1 ]; then
    # TODO: document usage
    echo "invalid number of parameters"
elif [ ! -f $2 ]; then
    export $1=$2
else
    mkdir /work/output
    cp $2 /work/output/$1
fi
