export const columnFilters = {
  name: 'string',
  title: 'string',
  revision: 'string',
  state: 'string',
  type: 'string',
  engine: 'string',
  dx_instance_class: 'string',
  dxInstanceClass: 'string',
  tags: 'string',
  status: 'string',
  featured: 'string',
  location: 'string',
  added_by: 'string',
  appTitle: 'string',
  launchedBy: 'string',
  file_size: 'range',
  workflowTitle: 'string',
  dxuser: 'string',
  email: 'string',
  userState: 'string',
  lastLogin: 'date_range',
  firstName: 'string',
  lastName: 'string',
  provisioningState: 'string',
  createdAt: 'date_range',
  role: 'number',
}
