export const columnFilters = {
  name: 'string',
  title: 'string',
  state: 'string',
  engine: 'string',
  dx_instance_class: 'string',
  tags: 'string',
  status: 'string',
  featured: 'string',
  location: 'string',
  added_by: 'string',
  app_title: 'string',
  launched_by: 'string',
  file_size: 'range',
  workflow_title: 'string',
}
