default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: password

development:
  <<: *default
  database: precisionfda-development

test:
  <<: *default
  database: precisionfda-test

production:
  <<: *default
  database: precisionfda-production
