default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: precisionfda-test
  host: localhost
  username: root
  password: root

production:
  <<: *default
  database: db/production.sqlite3
