# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3b2add3f971940ea4c3ccb1bf8eb0881b87f4245f37056eb11e5096b27d566ce82bf5c09ff92549d0d8a76997a6010c0ef475562d25dd26483093cc01dce01

test:
  secret_key_base: 02564fc207424c175e7ca61ec5abcbc5881004f5841e6b6af1cf9b083aa8f2680d5aa0f7d1b18a6515ee73d1211f905f77fba1e47a821f09c2974ee124c4cd77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
