# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc49f0f2aad42b4d1edf90236a2e0b82ccf0316dbf6e191a2329ef24cd695aada85b19a07eb3b64e87322401b49f38579f430707cd67a11c9ffd925c722d4b4

test:
  secret_key_base: 64c32c2a3e180ab5acb343c830f779ac5c3e2c4748ade7aea198bc8a359cb42a530f7abbf66379f4997e82970ed9f5c6f38329dae74e4455e21bddfece163087

ui_test:
  secret_key_base: 32c32c2a3e180ab5acb343c830f779ac5c3e2c4748ade7aea198bc8a359cb42a530f7abbf66379f4997e82970ed9f5c6f38329dae74e4455e21bddfece1630a1
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
