/* eslint-disable react/no-unescaped-entities */
import React from 'react'
import { useScrollToHash } from '../../../hooks/useScrollToHash'
import { DocBody, DocTable } from '../styles'

export const Tracking = () => {
  useScrollToHash()
  return (
    <DocBody>
      <h1>Tracking</h1>
      <p>
        Tracking is a precisionFDA feature that allows you to investigate the provenance of an item. Clicking the "Track" button
        from any page (file, app, job, database, comparison, note) generates a provenance graph. Each node in the graph denotes an
        item, and each line denotes a relationship between two items. A line connects from a source item towards a derived item,
        and it typically means "the source item is used as an ingredient in the derived item". The system keeps track of the
        following relationships:
      </p>
      <DocTable>
        <thead>
          <tr>
            <th>Derived item</th>
            <th>Source items / Ingredients</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>App</td>
            <td>The app's assets.</td>
          </tr>
          <tr>
            <td>Comparison</td>
            <td>The files that were used as inputs to the comparison.</td>
          </tr>
          <tr>
            <td>Database</td>
            <td>The creator of database.</td>
          </tr>
          <tr>
            <td>File</td>
            <td>The job that the file was generated from.</td>
          </tr>
          <tr>
            <td>Job</td>
            <td>The app that was run for the job, and the files that were used as inputs to the job.</td>
          </tr>
          <tr>
            <td>Note</td>
            <td>The note's attachments.</td>
          </tr>
        </tbody>
      </DocTable>
      <p>
        When generating the graph, the item currently being investigated is mostly at the top and is colored by a blue background.
        Its source items are under it, and their source items under them, etc. Items may contain multiple lines &mdash; for
        example an app that has been run multiple times &mdash; but following lines will always take you from top to bottom and
        never lead to any endless cycles. For complex cases, such as a note with many attachments, or a file generated by running
        a series of consecutive jobs, the graph may get very wide or very deep. In that case, use your browser's zoom feature to
        see more of the graph in your browser window, or scroll your browser's viewport accordingly.
      </p>
      <p>
        For items with outputs like Comparison and Job, the graph will display the output files, and these items will be
        positioned above the root node.
      </p>
      <p>
        The precisionFDA system uses the <a href="https://d3js.org">D3</a> library to lay out the graph in two dimensions. The
        library implements a layout algorithm which tries to minimize line crossings and other avoidable overlaps, but does not
        always produce optimal layouts.
      </p>
    </DocBody>
  )
}
