const FILES_LIST_RES = {
  results: [
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyzv0V00f24kgVbb3zBj1Bg9',
    },
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyzqyg80f24v2BJ93yq7yF4j',
    },
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyzqyg00f24f3qf940Pj7pfx',
    },
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyz77k80f24j1JB6332YgXKY',
    },
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyz76vj0f24xqYQ01vB7KZJY',
    },
    {
      project: 'project-FyxxYYj0f24VYQXy4QjPG2bB',
      id: 'file-Fyz76Q80f24p444q33Fg7ggz',
    },
  ],
  next: null,
} as const

const FILES_DESC_RES = {
  results: [
    {
      describe: {
        id: FILES_LIST_RES.results[0].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/.ipynb_checkpoints',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
    {
      describe: {
        id: FILES_LIST_RES.results[1].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
    {
      describe: {
        id: FILES_LIST_RES.results[2].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
    {
      describe: {
        id: FILES_LIST_RES.results[3].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
    {
      describe: {
        id: FILES_LIST_RES.results[4].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
    {
      describe: {
        id: FILES_LIST_RES.results[5].id,
        project: 'project-foo',
        class: 'file',
        sponsored: false,
        name: 'untitled-checkpoint.txt',
        types: [],
        state: 'closed',
        hidden: false,
        links: [],
        folder: '/',
        tags: [],
        created: 1606401885000,
        modified: 1606401886627,
        media: 'text/plain',
        size: 32,
      },
    },
  ],
} as const

export { FILES_LIST_RES, FILES_DESC_RES }
