export const EXPERTS_LIST_FETCH_START   = 'EXPERTS_LIST_FETCH_START'
export const EXPERTS_LIST_FETCH_SUCCESS = 'EXPERTS_LIST_FETCH_SUCCESS'
export const EXPERTS_LIST_FETCH_FAILURE = 'EXPERTS_LIST_FETCH_FAILURE'
export const EXPERTS_LIST_SET_PAGE = 'EXPERTS_LIST_SET_PAGE'
export const EXPERTS_LIST_SET_YEAR = 'EXPERTS_LIST_SET_YEAR'
export const EXPERTS_LIST_RESET_FILTERS = 'EXPERTS_LIST_RESET_FILTERS'

export const EXPERTS_YEAR_LIST_FETCH_START = 'EXPERTS_YEAR_LIST_FETCH_START'
export const EXPERTS_YEAR_LIST_FETCH_SUCCESS = 'EXPERTS_YEAR_LIST_FETCH_SUCCESS'
export const EXPERTS_YEAR_LIST_FETCH_FAILURE = 'EXPERTS_YEAR_LIST_FETCH_FAILURE'

export const EXPERTS_SHOW_MODAL = 'EXPERTS_SHOW_MODAL'
export const EXPERTS_HIDE_MODAL = 'EXPERTS_HIDE_MODAL'
