import { http, HttpResponse } from 'msw'

export const dbclusterMocks = [
  http.post('/api/dbclusters', () => HttpResponse.json({ 'db_cluster': { 'id': 28, 'dxid': 'dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'uid': 'dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F-1', 'name': 'Test', 'title': 'Test', 'status': 'creating', 'location': 'Private', 'scope_name': 'private', 'description': 'for testing only', 'added_by': 'Minch Yoda', 'added_by_fullname': 'Minch Yoda', 'created_at': '2023-01-30T12:17:28.296+01:00', 'created_at_date_time': '2023-01-30 12:17:28 CET', 'engine': 'aurora-mysql', 'engine_version': '5.7.mysql_aurora.2.07.10', 'dx_instance_class': 'db_std1_x2', 'status_as_of': '2023-01-30T12:17:28.000+01:00', 'status_updated_date_time': '2023-01-30 12:17:28 CET', 'host': null, 'port': null, 'show_license_pending': false, 'tags': [], 'links': { 'show': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'user': '/users/minch.yoda', 'create': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'update': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'attach_to': '/api/attach_to_notes', 'track': '/track?id=dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F-1', 'start': '/api/dbclusters/start', 'stop': '/api/dbclusters/stop', 'terminate': '/api/dbclusters/terminate' }, 'scope': 'private' } }, { status: 200 })),
  http.post('/api/dbclusters/stop', () => HttpResponse.json(null, { status: 204 })),
  http.get('/api/dbclusters', () => HttpResponse.json({
    'dbclusters': [
      { 'id': 27, 'dxid': 'dbcluster-GJVGV600JqyQ9pBj0698Fbbx', 'uid': 'dbcluster-GJVGV600JqyQ9pBj0698Fbbx-1', 'name': 'Test Terminated', 'title': 'Test Terminated', 'status': 'terminated', 'location': 'Private', 'scope_name': 'private', 'description': 'testing', 'added_by': 'Minch Yoda', 'added_by_fullname': 'Minch Yoda', 'created_at': '2022-11-02T20:44:25.168+01:00', 'created_at_date_time': '2022-11-02 20:44:25 CET', 'engine': 'aurora-mysql', 'engine_version': '5.7.mysql_aurora.2.07.10', 'dx_instance_class': 'db_std1_x2', 'status_as_of': '2022-11-02T21:34:23.000+01:00', 'status_updated_date_time': '2022-11-02 21:34:23 CET', 'host': 'dbcluster-gjvgv600jqyq9pbj0698fbbx.cluster-cfzitlm9q1kq.us-east-1.rds.amazonaws.com', 'port': '3306', 'show_license_pending': false, 'tags': [], 'links': { 'show': '/api/dbclusters/dbcluster-GJVGV600JqyQ9pBj0698Fbbx', 'user': '/users/minch.yoda', 'create': '/api/dbclusters/dbcluster-GJVGV600JqyQ9pBj0698Fbbx', 'update': '/api/dbclusters/dbcluster-GJVGV600JqyQ9pBj0698Fbbx', 'attach_to': '/api/attach_to_notes', 'track': '/track?id=dbcluster-GJVGV600JqyQ9pBj0698Fbbx-1', 'start': '/api/dbclusters/start', 'stop': '/api/dbclusters/stop', 'terminate': '/api/dbclusters/terminate' }, 'scope': 'private' },
      { 'id': 28, 'dxid': 'dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'uid': 'dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F-1', 'name': 'Test Creating', 'title': 'Test Creating', 'status': 'creating', 'location': 'Private', 'scope_name': 'private', 'description': 'for testing only', 'added_by': 'Minch Yoda', 'added_by_fullname': 'Minch Yoda', 'created_at': '2023-01-30T12:17:28.296+01:00', 'created_at_date_time': '2023-01-30 12:17:28 CET', 'engine': 'aurora-mysql', 'engine_version': '5.7.mysql_aurora.2.07.10', 'dx_instance_class': 'db_std1_x2', 'status_as_of': '2023-01-30T12:17:28.000+01:00', 'status_updated_date_time': '2023-01-30 12:17:28 CET', 'host': 'dbcluster-gpfpkvj0jqyqkvzgjyjjkf4f.cluster-cfzitlm9q1kq.us-east-1.rds.amazonaws.com', 'port': '3306', 'show_license_pending': false, 'tags': [], 'links': { 'show': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'user': '/users/minch.yoda', 'create': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'update': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'attach_to': '/api/attach_to_notes', 'track': '/track?id=dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F-1', 'start': '/api/dbclusters/start', 'stop': '/api/dbclusters/stop', 'terminate': '/api/dbclusters/terminate' }, 'scope': 'private' },
      { 'id': 29, 'dxid': 'dbcluster-GPLpKVj0JqyQKvZGjyjjkF5U', 'uid': 'dbcluster-GPLpKVj0JqyQKvZGjyjjkF5U-1', 'name': 'Test Available', 'title': 'Test Available', 'status': 'available', 'location': 'Private', 'scope_name': 'private', 'description': 'for testing only', 'added_by': 'Minch Yoda', 'added_by_fullname': 'Minch Yoda', 'created_at': '2023-01-30T12:17:28.296+01:00', 'created_at_date_time': '2023-01-30 12:17:28 CET', 'engine': 'aurora-mysql', 'engine_version': '5.7.mysql_aurora.2.07.10', 'dx_instance_class': 'db_std1_x2', 'status_as_of': '2023-01-30T12:33:33.000+01:00', 'status_updated_date_time': '2023-01-30 12:33:33 CET', 'host': 'dbcluster-gpfpkvj0jqyqkvzgjyjjkf4f.cluster-cfzitlm9q1kq.us-east-1.rds.amazonaws.com', 'port': '3306', 'show_license_pending': false, 'tags': [], 'links': { 'show': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'user': '/users/minch.yoda', 'create': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'update': '/api/dbclusters/dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F', 'attach_to': '/api/attach_to_notes', 'track': '/track?id=dbcluster-GPFpKVj0JqyQKvZGjyjjkF4F-1', 'start': '/api/dbclusters/start', 'stop': '/api/dbclusters/stop', 'terminate': '/api/dbclusters/terminate' }, 'scope': 'private' },
    ],
    'meta': { 'count': 6, 'pagination': { 'current_page': 1, 'next_page': null, 'prev_page': null, 'total_pages': 1, 'total_count': 6 } },
  }, { status: 200 })),
]