default: &default
  adapter: async

redis: &redis
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default

test:
  <<: *default

ui_test:
  <<: *default

dev:
  <<: *redis
  channel_prefix: pfda_dev

staging:
  <<: *redis
  channel_prefix: pfda_staging

production:
  <<: *redis
  channel_prefix: pfda_production
