export const spaceFilesSelector = (state) => state.spaces.files.entries
export const spacePathSelector = (state) => state.spaces.files.path
export const spaceFilesCheckedAllSelector = (state) => state.spaces.files.isCheckedAll
export const spaceIsFetchingFilesSelector = (state) => state.spaces.files.isFetching
export const spaceFilesListSortTypeSelector = (state) => state.spaces.files.sortType
export const spaceFilesListSortDirectionSelector = (state) => state.spaces.files.sortDirection
export const spaceFilesListPaginationSelector = (state) => state.spaces.files.pagination
export const spaceFilesAddFolderModalSelector = (state) => state.spaces.files.addFolderModal
export const spaceFilesActionModalSelector = (state) => state.spaces.files.actionModal
export const spaceFilesLinksSelector = (state) => state.spaces.files.links
export const spaceFilesRenameModalSelector = (state) => state.spaces.files.renameModal
export const spaceFilesCopyModalSelector = (state) => state.spaces.files.copyModal
export const spaceFilesMoveModalSelector = (state) => state.spaces.files.moveModal
