export const videos = [
  { title: 'Introduction', url: 'https://www.youtube.com/embed/U_vmcd93HkM' },
  { title: 'Discussions', url: 'https://www.youtube.com/embed/KHgUe-a1v_k' },
  { title: 'Notes', url: 'https://www.youtube.com/embed/c2-VlRxTZLM' },
  { title: 'How to Upload Files', url: 'https://www.youtube.com/embed/o5PmgUsWQGo' },
  { title: 'File & Folder Navigation', url: 'https://www.youtube.com/embed/cj8a6I3KGvk' },
  { title: 'Comparisons', url: 'https://www.youtube.com/embed/qMd98K07U9M' },
  { title: 'Running Apps', url: 'https://www.youtube.com/embed/P90E3jgL134' },
  { title: 'Batch Running Apps', url: 'https://www.youtube.com/embed/K9rHEef2FNs' },
  { title: 'Creating Apps', url: 'https://www.youtube.com/embed/f-DBLB2v1sM' },
  { title: 'Exploring and Forking Apps', url: 'https://www.youtube.com/embed/oQgJ9WD7Nkg' },
  { title: 'Exporting Apps', url: 'https://www.youtube.com/embed/WeF9uj9QJIo' },
  { title: 'Importing Apps', url: 'https://www.youtube.com/embed/4-voYR-q-cw' },
  { title: 'Workflows', url: 'https://www.youtube.com/embed/jGYNt1Vw_Wo' },
  { title: 'Publishing', url: 'https://www.youtube.com/embed/dsOCn1zTBOo' },
  { title: 'Licenses', url: 'https://www.youtube.com/embed/7iwwnKmalyM' },
  { title: 'Spaces', url: 'https://www.youtube.com/embed/-YfSmb_Y-gk' },
  { title: 'Review Spaces: Step by Step', url: 'https://www.youtube.com/embed/mPW82NtdKuo' },
]
