export const SPACES_FETCH_START = 'SPACES_FETCH_START'
export const SPACES_FETCH_SUCCESS = 'SPACES_FETCH_SUCCESS'
export const SPACES_FETCH_FAILURE = 'SPACES_FETCH_FAILURE'

export const SPACES_SWITCH_LIST_VIEW_TYPE = 'SPACES_SWITCH_LIST_VIEW_TYPE'

export const SPACES_SORT_SPACES_TABLE = 'SPACES_SORT_SPACES_TABLE'

export const SPACES_LIST_SEARCH = 'SPACES_LIST_SEARCH'

export const SPACES_LIST_RESET_FILTERS = 'SPACES_LIST_RESET_FILTERS'

export const SPACE_FETCH_START = 'SPACE_FETCH_START'
export const SPACE_FETCH_SUCCESS = 'SPACE_FETCH_SUCCESS'
export const SPACE_FETCH_FAILURE = 'SPACE_FETCH_FAILURE'

export const SPACE_LOCK_TOGGLE_START = 'SPACE_LOCK_TOGGLE_START'
export const SPACE_LOCK_TOGGLE_SUCCESS = 'SPACE_LOCK_TOGGLE_SUCCESS'
export const SPACE_LOCK_TOGGLE_FAILURE = 'SPACE_LOCK_TOGGLE_FAILURE'

export const SPACE_CREATION_START = 'SPACE_CREATION_START'
export const SPACE_CREATION_SUCCESS = 'SPACE_CREATION_SUCCESS'
export const SPACE_CREATION_FAILURE = 'SPACE_CREATION_FAILURE'

export const SPACE_CREATION_FETCH_INFO_START = 'SPACE_CREATION_FETCH_INFO_START'
export const SPACE_CREATION_FETCH_INFO_SUCCESS = 'SPACE_CREATION_FETCH_INFO_SUCCESS'
export const SPACE_CREATION_FETCH_INFO_FAILURE = 'SPACE_CREATION_FETCH_INFO_FAILURE'

export const SPACE_FILES_FETCH_START = 'SPACE_FILES_FETCH_START'
export const SPACE_FILES_FETCH_SUCCESS = 'SPACE_FILES_FETCH_SUCCESS'
export const SPACE_FILES_FETCH_FAILURE = 'SPACE_FILES_FETCH_FAILURE'

export const SPACE_FILES_TABLE_SORT = 'SPACE_FILES_TABLE_SORT'
export const SPACE_FILES_RESET_FILTERS = 'SPACE_FILES_RESET_FILTERS'
export const SPACE_FILES_SET_CURRENT_PAGE_VALUE = 'SPACE_FILES_SET_CURRENT_PAGE_VALUE'

export const SPACE_APPS_FETCH_START = 'SPACE_APPS_FETCH_START'
export const SPACE_APPS_FETCH_SUCCESS = 'SPACE_APPS_FETCH_SUCCESS'
export const SPACE_APPS_FETCH_FAILURE = 'SPACE_APPS_FETCH_FAILURE'

export const SPACE_APPS_TABLE_SORT = 'SPACE_APPS_TABLE_SORT'
export const SPACE_APPS_RESET_FILTERS = 'SPACE_APPS_RESET_FILTERS'
export const SPACE_APPS_SET_CURRENT_PAGE_VALUE = 'SPACE_APPS_SET_CURRENT_PAGE_VALUE'

export const SPACE_WORKFLOWS_FETCH_START = 'SPACE_WORKFLOWS_FETCH_START'
export const SPACE_WORKFLOWS_FETCH_SUCCESS = 'SPACE_WORKFLOWS_FETCH_SUCCESS'
export const SPACE_WORKFLOWS_FETCH_FAILURE = 'SPACE_WORKFLOWS_FETCH_FAILURE'

export const SPACE_WORKFLOWS_TABLE_SORT = 'SPACE_WORKFLOWS_TABLE_SORT'
export const SPACE_WORKFLOWS_RESET_FILTERS = 'SPACE_WORKFLOWS_RESET_FILTERS'
export const SPACE_WORKFLOWS_SET_CURRENT_PAGE_VALUE = 'SPACE_WORKFLOWS_SET_CURRENT_PAGE_VALUE'

export const SPACE_MEMBERS_FETCH_START = 'SPACE_MEMBERS_FETCH_START'
export const SPACE_MEMBERS_FETCH_SUCCESS = 'SPACE_MEMBERS_FETCH_SUCCESS'
export const SPACE_MEMBERS_FETCH_FAILURE = 'SPACE_MEMBERS_FETCH_FAILURE'
export const SPACE_MEMBERS_SHOW_ADD_MEMBERS_MODAL = 'SPACE_MEMBERS_SHOW_ADD_MEMBERS_MODAL'
export const SPACE_MEMBERS_HIDE_ADD_MEMBERS_MODAL = 'SPACE_MEMBERS_HIDE_ADD_MEMBERS_MODAL'
export const SPACE_MEMBERS_SHOW_ROLE_CHANGE_MODAL = 'SPACE_MEMBERS_SHOW_ROLE_CHANGE_MODAL'
export const SPACE_MEMBERS_HIDE_ROLE_CHANGE_MODAL = 'SPACE_MEMBERS_HIDE_ROLE_CHANGE_MODAL'
export const SPACE_MEMBERS_UPDATE_ROLE_START = 'SPACE_MEMBERS_UPDATE_ROLE_START'
export const SPACE_MEMBERS_UPDATE_ROLE_SUCCESS = 'SPACE_MEMBERS_UPDATE_ROLE_SUCCESS'
export const SPACE_MEMBERS_UPDATE_ROLE_FAILURE = 'SPACE_MEMBERS_UPDATE_ROLE_FAILURE'

export const SPACE_MEMBERS_ADD_START = 'SPACE_MEMBERS_ADD_START'
export const SPACE_MEMBERS_ADD_SUCCESS = 'SPACE_MEMBERS_ADD_SUCCESS'
export const SPACE_MEMBERS_ADD_FAILURE = 'SPACE_MEMBERS_ADD_FAILURE'

export const SPACE_JOBS_FETCH_START = 'SPACE_JOBS_FETCH_START'
export const SPACE_JOBS_FETCH_SUCCESS = 'SPACE_JOBS_FETCH_SUCCESS'
export const SPACE_JOBS_FETCH_FAILURE = 'SPACE_JOBS_FETCH_FAILURE'

export const SPACE_JOBS_TABLE_SORT = 'SPACE_JOBS_TABLE_SORT'
export const SPACE_JOBS_RESET_FILTERS = 'SPACE_JOBS_RESET_FILTERS'
export const SPACE_JOBS_SET_CURRENT_PAGE_VALUE = 'SPACE_JOBS_SET_CURRENT_PAGE_VALUE'

export const SPACE_SIDE_MENU_TOGGLE = 'SPACE_SIDE_MENU_TOGGLE'

export const SPACE_FILES_SHOW_ADD_FOLDER_MODAL = 'SPACE_FILES_SHOW_ADD_FOLDER_MODAL'
export const SPACE_FILES_HIDE_ADD_FOLDER_MODAL = 'SPACE_FILES_HIDE_ADD_FOLDER_MODAL'

export const SPACE_ACCEPT_START = 'SPACE_ACCEPT_START'
export const SPACE_ACCEPT_SUCCESS = 'SPACE_ACCEPT_SUCCESS'
export const SPACE_ACCEPT_FAILURE = 'SPACE_ACCEPT_FAILURE'

export const SPACE_LAYOUT_HIDE_CREATE_SPACE_MODAL = 'SPACE_LAYOUT_HIDE_CREATE_SPACE_MODAL'
export const SPACE_LAYOUT_SHOW_CREATE_SPACE_MODAL = 'SPACE_LAYOUT_SHOW_CREATE_SPACE_MODAL'

export const SPACE_LAYOUT_HIDE_LOCK_MODAL = 'SPACE_LAYOUT_HIDE_LOCK_MODAL'
export const SPACE_LAYOUT_SHOW_LOCK_MODAL = 'SPACE_LAYOUT_SHOW_LOCK_MODAL'

export const SPACE_LAYOUT_HIDE_UNLOCK_MODAL = 'SPACE_LAYOUT_HIDE_UNLOCK_MODAL'
export const SPACE_LAYOUT_SHOW_UNLOCK_MODAL = 'SPACE_LAYOUT_SHOW_UNLOCK_MODAL'

export const SPACE_LAYOUT_HIDE_DELETE_MODAL = 'SPACE_LAYOUT_HIDE_DELETE_MODAL'
export const SPACE_LAYOUT_SHOW_DELETE_MODAL = 'SPACE_LAYOUT_SHOW_DELETE_MODAL'

export const SPACE_FILES_TOGGLE_CHECKBOX = 'SPACE_FILES_TOGGLE_CHECKBOX'
export const SPACE_FILES_TOGGLE_ALL_CHECKBOXES = 'SPACE_FILES_TOGGLE_ALL_CHECKBOXES'

export const SPACES_SET_PAGE = 'SPACES_SET_PAGE'

export const LOCK_SPACE_START = 'LOCK_SPACE_START'
export const LOCK_SPACE_SUCCESS = 'LOCK_SPACE_SUCCESS'
export const LOCK_SPACE_FAILURE = 'LOCK_SPACE_FAILURE'

export const UNLOCK_SPACE_START = 'UNLOCK_SPACE_START'
export const UNLOCK_SPACE_SUCCESS = 'UNLOCK_SPACE_SUCCESS'
export const UNLOCK_SPACE_FAILURE = 'UNLOCK_SPACE_FAILURE'

export const DELETE_SPACE_START = 'DELETE_SPACE_START'
export const DELETE_SPACE_SUCCESS = 'DELETE_SPACE_SUCCESS'
export const DELETE_SPACE_FAILURE = 'DELETE_SPACE_FAILURE'

export const SPACE_FILES_SHOW_ACTION_MODAL = 'SPACE_FILES_SHOW_ACTION_MODAL'
export const SPACE_FILES_HIDE_ACTION_MODAL = 'SPACE_FILES_HIDE_ACTION_MODAL'

export const SPACE_FETCH_FILES_BY_ACTION_START = 'SPACE_FETCH_FILES_BY_ACTION_START'
export const SPACE_FETCH_FILES_BY_ACTION_SUCCESS = 'SPACE_FETCH_FILES_BY_ACTION_SUCCESS'
export const SPACE_FETCH_FILES_BY_ACTION_FAILURE = 'SPACE_FETCH_FILES_BY_ACTION_FAILURE'

export const SPACE_DELETE_FILES_START = 'SPACE_DELETE_FILES_START'
export const SPACE_DELETE_FILES_SUCCESS = 'SPACE_DELETE_FILES_SUCCESS'
export const SPACE_DELETE_FILES_FAILURE = 'SPACE_DELETE_FILES_FAILURE'

export const SPACE_PUBLISH_FILES_START = 'SPACE_PUBLISH_FILES_START'
export const SPACE_PUBLISH_FILES_SUCCESS = 'SPACE_PUBLISH_FILES_SUCCESS'
export const SPACE_PUBLISH_FILES_FAILURE = 'SPACE_PUBLISH_FILES_FAILURE'

export const SPACE_FILES_SHOW_RENAME_MODAL = 'SPACE_FILES_SHOW_RENAME_MODAL'
export const SPACE_FILES_HIDE_RENAME_MODAL = 'SPACE_FILES_HIDE_RENAME_MODAL'

export const SPACE_RENAME_FILE_START = 'SPACE_RENAME_FILE_START'
export const SPACE_RENAME_FILE_SUCCESS = 'SPACE_RENAME_FILE_SUCCESS'
export const SPACE_RENAME_FILE_FAILURE = 'SPACE_RENAME_FILE_FAILURE'

export const SPACE_SHOW_ADD_DATA_MODAL = 'SPACE_SHOW_ADD_DATA_MODAL'
export const SPACE_HIDE_ADD_DATA_MODAL = 'SPACE_HIDE_ADD_DATA_MODAL'

export const SPACE_ADD_FOLDER_START = 'SPACE_ADD_FOLDER_START'
export const SPACE_ADD_FOLDER_SUCCESS = 'SPACE_ADD_FOLDER_SUCCESS'
export const SPACE_ADD_FOLDER_FAILURE = 'SPACE_ADD_FOLDER_FAILURE'

export const SPACE_FILES_SHOW_COPY_MODAL = 'SPACE_FILES_SHOW_COPY_MODAL'
export const SPACE_FILES_HIDE_COPY_MODAL = 'SPACE_FILES_HIDE_COPY_MODAL'

export const FETCH_ACCESSIBLE_SPACES_START = 'FETCH_ACCESSIBLE_SPACES_START'
export const FETCH_ACCESSIBLE_SPACES_SUCCESS = 'FETCH_ACCESSIBLE_SPACES_SUCCESS'
export const FETCH_ACCESSIBLE_SPACES_FAILURE = 'FETCH_ACCESSIBLE_SPACES_FAILURE'

export const SPACE_SELECT_ACCESSIBLE_SPACE = 'SPACE_SELECT_ACCESSIBLE_SPACE'

export const COPY_OBJECTS_TO_SPACE_START = 'COPY_OBJECTS_TO_SPACE_START'
export const COPY_OBJECTS_TO_SPACE_SUCCESS = 'COPY_OBJECTS_TO_SPACE_SUCCESS'
export const COPY_OBJECTS_TO_SPACE_FAILURE = 'COPY_OBJECTS_TO_SPACE_FAILURE'

export const COPY_FILES_TO_PRIVATE_START = 'COPY_FILES_TO_PRIVATE_START'
export const COPY_FILES_TO_PRIVATE_SUCCESS = 'COPY_FILES_TO_PRIVATE_SUCCESS'
export const COPY_FILES_TO_PRIVATE_FAILURE = 'COPY_FILES_TO_PRIVATE_FAILURE'

export const COPY_APPS_TO_PRIVATE_START = 'COPY_APPS_TO_PRIVATE_START'
export const COPY_APPS_TO_PRIVATE_SUCCESS = 'COPY_APPS_TO_PRIVATE_SUCCESS'
export const COPY_APPS_TO_PRIVATE_FAILURE = 'COPY_APPS_TO_PRIVATE_FAILURE'

export const FETCH_ACCESSIBLE_FILES_START = 'FETCH_ACCESSIBLE_FILES_START'
export const FETCH_ACCESSIBLE_FILES_SUCCESS = 'FETCH_ACCESSIBLE_FILES_SUCCESS'
export const FETCH_ACCESSIBLE_FILES_FAILURE = 'FETCH_ACCESSIBLE_FILES_FAILURE'

export const FETCH_ACCESSIBLE_APPS_START = 'FETCH_ACCESSIBLE_APPS_START'
export const FETCH_ACCESSIBLE_APPS_SUCCESS = 'FETCH_ACCESSIBLE_APPS_SUCCESS'
export const FETCH_ACCESSIBLE_APPS_FAILURE = 'FETCH_ACCESSIBLE_APPS_FAILURE'

export const FETCH_ACCESSIBLE_WORKFLOWS_START = 'FETCH_ACCESSIBLE_WORKFLOWS_START'
export const FETCH_ACCESSIBLE_WORKFLOWS_SUCCESS = 'FETCH_ACCESSIBLE_WORKFLOWS_SUCCESS'
export const FETCH_ACCESSIBLE_WORKFLOWS_FAILURE = 'FETCH_ACCESSIBLE_WORKFLOWS_FAILURE'

export const SPACE_FILES_ADD_DATA_TOGGLE_CHECKBOX = 'SPACE_FILES_ADD_DATA_TOGGLE_CHECKBOX'
export const SPACE_FILES_ADD_DATA_TOGGLE_ALL_CHECKBOXES = 'SPACE_FILES_ADD_DATA_TOGGLE_ALL_CHECKBOXES'

export const SPACE_APPS_ADD_DATA_TOGGLE_CHECKBOX = 'SPACE_APPS_ADD_DATA_TOGGLE_CHECKBOX'
export const SPACE_APPS_ADD_DATA_TOGGLE_ALL_CHECKBOXES = 'SPACE_APPS_ADD_DATA_TOGGLE_ALL_CHECKBOXES'

export const SPACE_WORKFLOWS_ADD_DATA_TOGGLE_CHECKBOX = 'SPACE_WORKFLOWS_ADD_DATA_TOGGLE_CHECKBOX'
export const SPACE_WORKFLOWS_ADD_DATA_TOGGLE_ALL_CHECKBOXES = 'SPACE_WORKFLOWS_ADD_DATA_TOGGLE_ALL_CHECKBOXES'

export const ADD_DATA_TO_SPACE_START = 'ADD_DATA_TO_SPACE_START'
export const ADD_DATA_TO_SPACE_SUCCESS = 'ADD_DATA_TO_SPACE_SUCCESS'
export const ADD_DATA_TO_SPACE_FAILURE = 'ADD_DATA_TO_SPACE_FAILURE'

export const SPACE_EDITING_START = 'SPACE_EDITING_START'
export const SPACE_EDITING_SUCCESS = 'SPACE_EDITING_SUCCESS'
export const SPACE_EDITING_FAILURE = 'SPACE_EDITING_FAILURE'

export const SPACE_APPS_TOGGLE_CHECKBOX = 'SPACE_APPS_TOGGLE_CHECKBOX'
export const SPACE_APPS_TOGGLE_ALL_CHECKBOXES = 'SPACE_APPS_TOGGLE_ALL_CHECKBOXES'

export const SPACE_WORKFLOWS_TOGGLE_CHECKBOX = 'SPACE_WORKFLOWS_TOGGLE_CHECKBOX'
export const SPACE_WORKFLOWS_TOGGLE_ALL_CHECKBOXES = 'SPACE_WORKFLOWS_TOGGLE_ALL_CHECKBOXES'

export const SPACE_APPS_SHOW_COPY_MODAL = 'SPACE_APPS_SHOW_COPY_MODAL'
export const SPACE_APPS_HIDE_COPY_MODAL = 'SPACE_APPS_HIDE_COPY_MODAL'

export const SPACE_WORKFLOWS_SHOW_COPY_MODAL = 'SPACE_WORKFLOWS_SHOW_COPY_MODAL'
export const SPACE_WORKFLOWS_HIDE_COPY_MODAL = 'SPACE_WORKFLOWS_HIDE_COPY_MODAL'
