class AppsController < ApplicationController
  skip_before_action :require_login,     only: [:index, :featured, :explore, :show, :fork, :new]
  before_action :require_login_or_guest, only: [:index, :featured, :explore, :show, :fork, :new]

  def index
    if @context.guest?
      redirect_to explore_apps_path
      return
    end

    js_param = {}
    @app = nil
    if params[:id].present?
      @app = App.accessible_by(@context).find_by(dxid: params[:id])
      if @app.nil?
        flash[:error] = "Sorry, this app does not exist or is not accessible by you"
        redirect_to apps_path
        return
      else
        @items_from_params = [@app]
        @item_path = pathify(@app)
        @item_comments_path = pathify_comments(@app)
        @comments = @app.root_comments.order(id: :desc).page params[:comments_page]

        @revisions = @app.app_series.accessible_revisions(@context).select(:title, :id, :dxid, :revision, :version)
        @notes = @app.notes.real_notes.accessible_by(@context).order(id: :desc).page params[:notes_page]
        @answers = @app.notes.accessible_by(@context).answers.order(id: :desc).page params[:answers_page]
        @discussions = @app.notes.accessible_by(@context).discussions.order(id: :desc).page params[:discussions_page]
      end
      js_param[:app] = @app.slice(:id, :dxid, :readme)
    end

    @my_apps = AppSeries.editable_by(@context).order(name: :asc).map { |s| s.latest_accessible(@context) }.reject(&:nil?)

    @ran_apps = AppSeries.accessible_by(@context).order(name: :asc).where.not(user_id: @context.user_id).joins(:jobs).distinct.where(:jobs => { :user_id => @context.user_id }).map { |s| s.latest_accessible(@context) }.reject(&:nil?)


    User.sync_jobs!(@context)
    if @app.present?
      jobs = @app.app_series.jobs.editable_by(@context)
    else
      jobs = Job.editable_by(@context)
    end
    @jobs_grid = initialize_grid(jobs.includes(:taggings), {
      name: 'jobs',
      order: 'jobs.id',
      order_direction: 'desc',
      per_page: 100,
      include: [{taggings: :tag}]
    })
    js js_param
  end

  def export
    # App should exist and be accessible
    app = App.accessible_by(@context).find_by!(dxid: params[:id])

    # Assets should be accessible and licenses accepted
    if app.assets.accessible_by(@context).count != app.assets.count
      flash[:error] = "This app cannot be exported because one or more assets are not accessible by the current user."
      redirect_to app_path(app.dxid)
      return
    end
    if app.assets.any? { |a| a.license.present? && !a.licensed_by?(@context) }
      flash[:error] = "This app contains one or more assets which need to be licensed. Please run the app first in order to accept the licenses."
      redirect_to app_path(app.dxid)
      return
    end

    # Generate Dockerfile for app
    cmds = []
    cmds << "# Generated by precisionFDA exporter (v1.0.1) on #{Time.now.to_s}"
    cmds << "# The links and authorization tokens in this file are valid only for 24h."
    cmds << ""
    cmds << "# Exported app: #{app.name}, revision: #{app.revision}, authored by: #{app.user.username}"
    cmds << "# #{app_url(app.dxid)}"
    cmds << ""
    cmds << "# For more information please consult the app export section in the precisionFDA docs"
    cmds << ""
    cmds << "# Start with Ubuntu 14.04 base image"
    cmds << "FROM ubuntu:14.04"
    cmds << ""

    apt_packages = [
      "aria2",
      "byobu",
      "cmake",
      "cpanminus",
      "curl",
      "dstat",
      "g++",
      "git",
      "htop",
      "libboost-all-dev",
      "libcurl4-openssl-dev",
      "libncurses5-dev",
      "make",
      "perl",
      "pypy",
      "python-dev",
      "python-pip",
      "r-base",
      "ruby1.9.3",
      "wget",
      "xz-utils"
    ]
    cmds << "# Install default precisionFDA Ubuntu packages"
    cmds << "RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \\\n\t#{apt_packages.join(" \\\n\t")}"
    cmds << ""

    python_packages = [
      "requests==2.5.0",
      "futures==2.2.0",
      "setuptools==10.2"
    ]
    cmds << "# Install default precisionFDA python packages"
    cmds << "RUN pip install \\\n\t#{python_packages.join(" \\\n\t")}"
    cmds << ""

    cmds << "# Add DNAnexus repo to apt-get"
    cmds << "RUN /bin/bash -c \"echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list\""
    cmds << "RUN /bin/bash -c \"echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list\""
    cmds << "RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -"
    cmds << ""

    # Generate Docker command for installing apt-packages
    if app.packages.present?
      cmds << "# Install app-specific Ubuntu packages"
      cmds << "RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \\\n\t#{app.packages.join(" \\\n\t")}"
    else
      cmds << "# Update apt-get"
      cmds << "RUN DEBIAN_FRONTEND=noninteractive apt-get update"
    end
    cmds << ""

    # Generate download URLs and Docker commands for each asset
    if app.assets.present?
      cmds << "# Download app assets"
      app.assets.sort_by { |asset| app.ordered_assets.find_index(asset.dxid) }.each do |asset|
        url = DNAnexusAPI.new(@context.token).call(asset.dxid, "download", {filename: asset.name, project: asset.project, preauthenticated: true})["url"]
        tar_opts = asset.is_gzipped? ? 'xzf -' : 'xf -'
        cmds << "RUN curl #{url} | tar #{tar_opts} -C / --no-same-owner --no-same-permissions"
      end
      cmds << ""
    end

    cmds << "# Download pfda executables"
    cmds << "RUN curl https://dl.dnanex.us/F/D/p59772Gz0B3V9F456z26bFxk8GqqXJfF7YQ8Ypk4/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions"
    cmds << "RUN curl https://dl.dnanex.us/F/D/J6yqF2Jy1yY377kFpkqBz8kb78k6yxVy376xxj9B/pfda-1.0.6.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions"
    cmds << "RUN curl https://dl.dnanex.us/F/D/0kKgz424jbV1v5bvGK5738V9g5y72bJK3BGfQ3VJ/run-1.1.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions"
    cmds << ""

    # Generate new token for pfda uploader
    context = @context.as_json.slice("user_id", "username", "token", "expiration", "org_id")
    context["expiration"] = [context["expiration"], Time.now.to_i + 1.day].min
    key = rails_encryptor.encrypt_and_sign({context: context}.to_json)

    # Generate Docker command for running pfda uploader to pull app info
    cmds << "# Download app spec and code"
    cmds << "RUN pfda --auth #{key} download-app-spec --app-id=#{app.dxid} --output-file=\"/spec.json\""
    cmds << "RUN pfda --auth #{key} download-app-script --app-id=#{app.dxid} --output-file=\"/script.sh\""
    cmds << ""

    cmds << "# Create directory /work and set it to $HOME and CWD"
    cmds << "RUN mkdir -p /work"
    cmds << "ENV HOME=\"/work\""
    cmds << "WORKDIR /work"
    cmds << ""

    # Add entry point to container
    cmds << "# Set entry point to container"
    cmds << "ENTRYPOINT [\"/usr/bin/run\"]"
    cmds << ""

    dockerfile = cmds.join("\n")    # Join with newlines

    # Download string as Dockerfile
    send_data dockerfile, :type => 'text; charset=utf-8', :disposition => 'attachment', :filename => 'Dockerfile'
  end

  def featured
    org = Org.featured
    if org
      @apps_grid = initialize_grid(AppSeries.accessible_by_public.include(:user, :taggings).where(:users => { :org_id => org.id }), {
        name: 'apps',
        order: 'apps.created_at',
        order_direction: 'desc',
        per_page: 100,
        include: [{user: :org}, :latest_version_app, {taggings: :tag}]
      })
    end
    render :list
  end

  def explore
    @apps_grid = initialize_grid(AppSeries.accessible_by_public.includes( :latest_version_app, :taggings), {
      name: 'apps',
      order: 'apps.created_at',
      order_direction: 'desc',
      per_page: 100,
      include: [{user: :org}, :latest_version_app, {taggings: :tag}]
    })
    render :list
  end

  def show
    @app = App.accessible_by(@context).find_by(dxid: params[:id])
    if @app.nil?
      flash[:error] = "Sorry, this app does not exist or is not accessible by you"
      redirect_to apps_path
      return
    end

    @revisions = @app.app_series.accessible_revisions(@context).select(:title, :id, :dxid, :revision, :version)
    @notes = @app.notes.real_notes.accessible_by(@context).order(id: :desc).page params[:notes_page]
    @answers = @app.notes.accessible_by(@context).answers.order(id: :desc).page params[:answers_page]
    @discussions = @app.notes.accessible_by(@context).discussions.order(id: :desc).page params[:discussions_page]

    @items_from_params = [@app]
    @item_path = pathify(@app)
    @item_comments_path = pathify_comments(@app)
    @comments = @app.root_comments.order(id: :desc).page params[:comments_page]

    User.sync_jobs!(@context)

    jobs = @app.app_series.jobs.editable_by(@context)
    @jobs_grid = initialize_grid(jobs, {
      name: 'jobs',
      order: 'jobs.id',
      order_direction: 'desc',
      per_page: 100
    })

    js app: @app.slice(:id, :dxid, :readme)
  end

  def edit
    @app = App.editable_by(@context).find_by(dxid: params[:id])
    if @app.nil?
      flash[:error] = "Sorry, this app does not exist or is not accessible by you"
      redirect_to apps_path
      return
    else
      if @app.id != @app.app_series.latest_revision_app_id
        redirect_to edit_app_path(@app.app_series.latest_revision_app.dxid)
        return
      else
        js app: @app.slice(:dxid, :name, :title, :version, :revision, :readme, :spec, :internal)
      end
    end
  end

  def new
  end

  def fork
    @app = App.accessible_by(@context).find_by(dxid: params[:id])
    if @app.nil?
      flash[:error] = "Sorry, you do not have permissions to fork this app"
      redirect_to apps_path
      return
    else
      js app: @app.slice(:dxid, :name, :title, :version, :revision, :readme, :spec, :internal)
    end
  end
end
