services:
  default:
    pfda-nodejs-api:
      imageName: server
      desiredCount: 1
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 3001
      serviceConnect:
        securityGroups:
          - name: common-sg
      command: ["pnpm", "run", "start:prod:api"]
      healthCheck:
        command: ["CMD-SHELL", "curl -kf https://localhost:3001/health || exit 1"]
        interval: 30
        timeout: 5
        retries: 3
        startPeriod: 60
      xray_enabled: true

    pfda-nodejs-api-internal:
      imageName: server
      desiredCount: 1
      container:
        cpu: 512
        memoryReservation: 1024
      containerPort: 3001
      serviceConnect:
        securityGroups:
          - name: api-internal-sg
      command: ["npm", "run", "start:prod:api", "--", "--internal"]
      healthCheck:
        command: ["CMD-SHELL", "curl -kf https://localhost:3001/health || exit 1"]
        interval: 30
        timeout: 5
        retries: 3
        startPeriod: 60
      xray_enabled: true

    pfda-nodejs-worker:
      imageName: server
      desiredCount: 2
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 3001
      serviceConnect:
        securityGroups:
          - name: common-sg
      command: ["pnpm", "run", "start:prod:worker"]
      xray_enabled: true

    pfda-nodejs-admin-platform-client:
      imageName: server
      desiredCount: 2
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 3002
      serviceConnect:
        securityGroups:
          - name: common-sg
      command: ["pnpm", "run", "start:prod:admin-platform-client"]
      xray_enabled: true


    pfda-db-migrate:
      imageName: web
      desiredCount: 0  # not a running service; run as needed
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 3000
      command: ["bundle", "exec", "rake", "db:migrate"]
      serviceConnect:
        securityGroups:
          - name: common-sg

    pfda-web:
      imageName: web
      desiredCount: 2
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 3000
      serviceConnect:
        securityGroups:
          - name: web-sg
      xray_enabled: true

    pfda-docs:
      imageName: docs
      desiredCount: 1
      container:
        cpu: 128
        memoryReservation: 256
      containerPort: 4040
      serviceConnect:
        securityGroups:
          - name: common-sg

    pfda-nginx:
      imageName: nginx
      desiredCount: 1
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 443
      serviceConnect:
        securityGroups:
          - name: nginx-sg
      targetGroupName: ecs-default-tg


    gsrs-web:
      imageName: gsrs_web
      desiredCount: 1
      container:
        cpu: 1664
        memoryReservation: 6144
      containerPort: 8080
      privileged: true
      serviceConnect:
        securityGroups:
          - name: gsrs-web-sg

      volumes:
        - name: read-only-base-index
          host:
            sourcePath: /opt/gsrs/base_index
        - name: overlay-data-index
          host:
            sourcePath: /opt/gsrs/overlay-data

      mountPoints:
        - sourceVolume: read-only-base-index
          containerPath: /tmp/read-only-base
          readOnly: true
        - sourceVolume: overlay-data-index
          containerPath: /tmp/overlay-data
          readOnly: false

    gsrs-nginx:
      imageName: gsrs_nginx
      desiredCount: 1
      container:
        cpu: 256
        memoryReservation: 512
      containerPort: 80
      serviceConnect:
        securityGroups:
          - name: gsrs-nginx-sg
      targetGroupName: assets-ecs-tg

############ ENV OVERRIDE ############

  dev:
    pfda-nodejs-worker:
      desiredCount: 1
    pfda-nodejs-admin-platform-client:
      desiredCount: 1
    pfda-web:
      desiredCount: 1

  test:
    pfda-nodejs-worker:
      desiredCount: 1
    pfda-nodejs-admin-platform-client:
      desiredCount: 1
    pfda-web:
      desiredCount: 1

  staging:
    pfda-nodejs-api:
      desiredCount: 2
      container:
        cpu: 512
        memoryReservation: 1024
    pfda-nodejs-worker:
      desiredCount: 4
      container:
        cpu: 512
        memoryReservation: 1024
    pfda-nodejs-api-internal:
      desiredCount: 2
      container:
        cpu: 512
        memoryReservation: 1024


