#!/bin/bash

if [ "$#" -le 1 ]; then
    # TODO: document usage
    echo "invalid number of parameters"
elif [ ! -f $2 ]; then
    echo -- "$2" > /output/$1
else
    mkdir -p /output
    cp -- "$2" /output/"$1"
fi
