version: '3.7'

services:
  web:
    environment:
      - ARM64V8_DEVELOPMENT_PATCH=1
      - RAILS_ENV=development
  nodejs-api:
    build:
      dockerfile: ./https-apps-api/docker/node.isolated-dev.Dockerfile
    command: ['make', 'watch']
    volumes:
      - type: bind
        source: ../../https-apps-api
        target: /app
    environment:
      - NODE_ENV=development
      - NODE_DATABASE_NAME=precision-fda
      - NODE_DATABASE_URL=mysql://root:password@db:3306/precision-fda

  nodejs-worker:
    build:
      dockerfile: ./https-apps-api/docker/node.isolated-dev.Dockerfile
    command: ['make', 'watch-worker']
    volumes:
      - type: bind
        source: ../../https-apps-api
        target: /app
    environment:
      - NODE_ENV=development
      - NODE_DATABASE_NAME=precision-fda
      - NODE_DATABASE_URL=mysql://root:password@db:3306/precision-fda
