name: RUN - GSRS Data Update

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: Deployment Environment
        type: choice
        options:
          - dev_8517
          - test_4711
          - staging_4711
          - production
        default: dev_8517
      SKIP_DB_UPDATE:
        description: Skip Database Update
        type: boolean
        default: false
      SKIP_INDEX_UPDATE:
        description: Skip Index Update
        type: boolean
        default: false

concurrency:
  group: ${{inputs.ENVIRONMENT}}-gsrs-data-update
  cancel-in-progress: false

run-name: GSRS DATA update ENV=${{ inputs.ENVIRONMENT }}
jobs:
  build-and-push-gsrs-images:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    outputs:
      gsrs_data_update_image_tag: ${{ steps.set_output.outputs.gsrs_data_update_image_tag }}
    strategy:
      matrix:
        include:
          - package: gsrs_data_update
            context: "packages/gsrs/data_update"
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - uses: ./.github/actions/build-gsrs-docker-images
        id: build_image
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.REGION }}
          role-arn: ${{ vars.ROLE_ECS_GITHUB_ARN }}
          orchestration-account-id: ${{ vars.ORCHESTRATION_ACCOUNT_ID }}
          package: ${{ matrix.package }}
          context: ${{ matrix.context }}

      - name: Set matrix job output
        id: set_output
        run: |
          echo "${{ matrix.package }}_image_tag=${{ steps.build_image.outputs.image-tag }}" >> $GITHUB_OUTPUT

      - name: Write build summary
        run: |
          {
            echo "### 📦 Built Image"
            echo "- **Component:** ${{ matrix.package }}"
            echo "- **Final Tag:** ${{ steps.build_image.outputs.image-tag }}"
          } >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: build-and-push-gsrs-images
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Python 3.11
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pyaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.ROLE_ECS_GITHUB_ARN }}

      - name: Get AWS Account ID
        id: get_account_id
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          echo "AWS Account ID: $ACCOUNT_ID"
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: Set SSM Parameters
        run: |
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/app/environment/GSRS_SKIP_DB_UPDATE --value '${{ inputs.SKIP_DB_UPDATE }}' --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/app/environment/GSRS_SKIP_INDEX_UPDATE --value '${{ inputs.SKIP_INDEX_UPDATE }}' --overwrite >/dev/null

      - name: Run GSRS Data Update
        working-directory: infra/ecs
        env:
          AWS_REGION: ${{ vars.REGION }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          GSRS_DATA_UPDATE_TAG: ${{ needs.build-and-push-gsrs-images.outputs.gsrs_data_update_image_tag }}
          FORCE_DEPLOY_SERVICES: "gsrs-data-update"
          GIT_BRANCH: ${{ github.ref_name }}
          DEPLOYMENT_TYPE: "gsrs"
          PYTHONUNBUFFERED: "1"
          WAIT_FOR_COMPLETION: "false"
        run: |
          echo "Deploying GSRS to $ENVIRONMENT..."
          echo "GSRS_DATA_UPDATE_TAG=$GSRS_DATA_UPDATE_TAG"

          python deploy-ecs-service.py
        shell: bash