# Project Docs: https://confluence.internal.dnanexus.com/pages/viewpage.action?pageId=20124178

name: Master Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Full Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Build
        run: bundle install --jobs 4 --retry 3

# To be returned after global Rubocop lint fix
#      - name: Lint
#        run: rubocop

      - name: Brakeman
        run: brakeman -A --parser-timeout 30 -o gha_out/brakeman.html -w2

  test:
    name: Test
    runs-on: ubuntu-latest
    container: ruby:2.7.1

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: Install & Build
        run: |
          apt-get update
          apt-get install -y cmake libssl-dev
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3

      - name: Configure
        env:
          NO_FIPS: 1
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:setup

      - name: Create fake bundles
        run: |
          mkdir app/assets/packs
          touch app/assets/packs/bundle.js
          touch app/assets/packs/bundle.css

      - name: Unit Tests
        env:
          NO_FIPS: 1
        run: bundle exec rspec

  checkDependencies:
    name: Dependencies Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk
        uses: snyk/actions/ruby@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=Gemfile.lock --org=dnanexus

      - name: Publish
        if: always()
        uses: snyk/actions/ruby@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=Gemfile.lock --org=dnanexus --project-name=precision-fda
          command: monitor

  test-js:
    name: Test (JS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Install
        run: yarn

      - name: Test
        run: yarn test

  test-nodejs-api:
    name: Test HTTPS Apps api
    runs-on: ubuntu-latest
    container: ruby:2.7.1

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password

    env:
      NODE_ENV: test
      DATABASE_TEST_URL: mysql://root:password@mysql:3306/test_db
      DATABASE_TEST_NAME: test_db

    steps:
      - uses: actions/checkout@v2
      # we have to get the database to same state as for RoR app
      - name: Install & Build
        run: |
          apt-get update
          apt-get install -y cmake libssl-dev
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      - name: Configure
        env:
          NO_FIPS: 1
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:setup
      - name: Install yarn
        run: npm install -g yarn
      - run: cd ./https-apps-api && make install
      - run: cd ./https-apps-api && make test-api
      - run: cd ./https-apps-api && make test-worker
      - name: Snyk test
        run: cd ./https-apps-api && ./node_modules/.bin/snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  react-app:
    name: React App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Install
        run: yarn --frozen-lockfile
        working-directory: ./client

      - name: Test
        run: yarn test
        working-directory: ./client

      - name: Lint
        run: yarn lint .
        working-directory: ./client
