# Project Docs: https://confluence.internal.dnanexus.com/pages/viewpage.action?pageId=20124178

name: Master Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Full Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Build
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Lint
        run: rubocop

      - name: Brakeman
        run: brakeman -A --parser-timeout 30 -o gha_out/brakeman.html -w2

      - name: Rails Best Practices
        run: rails_best_practices

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: staticAnalysis # Skip this if static analysis failed
    container: ruby:2.6.5

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - name: Install & Build
        run: |
          apt-get update
          apt-get install -y cmake libssl-dev
          gem install bundler -v 2.1.4
          bundle install --jobs 4 --retry 3

      - name: Configure
        env:
          NO_FIPS: 1
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rake db:setup

      - name: Unit Tests
        env:
          NO_FIPS: 1
        run: bundle exec rake

  checkDependencies:
    name: Dependencies Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk
        uses: snyk/actions/ruby@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=Gemfile.lock --org=dnanexus

      - name: Publish
        if: always()
        uses: snyk/actions/ruby@0.1.1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=Gemfile.lock --org=dnanexus --project-name=precision-fda
          command: monitor
