name: STAGING - Deploy GSRS to AWS

on:
  workflow_dispatch:
    inputs:
      GSRS_BRANCH:
        description: GSRS Revision
        type: string
        default: gsrs_250425
      GSRS_DATABASE_NAME:
        description: GSRS Database and Index Name
        type: string
        default: ixginas20250829
      LT_VERSION:
        description: Launch Template Version
        type: string
        default: $Default

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

run-name: ${{ github.event_name == 'workflow_dispatch' && format('{0} | GSRS_BRANCH={1}, GSRS_DATABASE_NAME={2}, LT_VERSION={3}', github.workflow, inputs.GSRS_BRANCH, inputs.GSRS_DATABASE_NAME, inputs.LT_VERSION) || '' }}
jobs:
  deploy:
    name: deploy to AWS
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: staging_4711

    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
   
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.ROLE_GSRS_ARN }}

      - name: Set SSM Parameters
        run: |
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/chef/source_branch --value '${{ github.ref_name }}' --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/gsrs/revision --value '${{ inputs.GSRS_BRANCH }}' --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/gsrs/database_name --value '${{ inputs.GSRS_DATABASE_NAME }}' --overwrite >/dev/null

      - name: Run deploy.sh script
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          AWS_REGION: ${{ vars.REGION }}
          ENV_ATTEMPTS: ${{ vars.ENV_ATTEMPTS }}
          ENV_SUBNET1: ${{ vars.ENV_SUBNET1 }}
          ENV_SUBNET2: ${{ vars.ENV_SUBNET2 }}
          ENV_SUBNET3: ${{ vars.ENV_SUBNET3 }}
          ENV_ASG_NAME: ${{ vars.ENV_GSRS_ASG_NAME }}
          ENV_TG: ${{ vars.ENV_GSRS_TG }} ${{ vars.ENV_GSRS_STATIG_ASSETS_TG }}
          ENV_LT_NAME: ${{ vars.ENV_GSRS_LT_NAME }}
          ENV_LT_VERSION: ${{ inputs.LT_VERSION }}
          ENV_INSTANCE_TYPE: gsrsinstance
          ENV_MIN_SIZE: ${{ vars.ENV_GSRS_MIN_SIZE }}
          ENV_MAX_SIZE: ${{ vars.ENV_GSRS_MAX_SIZE }}
          ENV_DESIRED_CAP: ${{ vars.ENV_GSRS_DESIRED_CAP }}
        run: ./infra/deploy.sh
