name: TEST - Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      GSRS_ENABLED:
        description: GSRS enabled
        type: boolean
        default: true
      GSRS_BRANCH:
        description: GSRS revision
        type: string
        default: gsrs_240919
      CHEF_RUNLIST:
        description: Chef Runlist
        type: string
        default: "role[pfda_server]"
      CHEF_ATTRIBUTES:
        description: Chef Attributes
        type: string
        default: '{"ssm_base_path": "/pfda/test"}'
      LT_VERSION:
        description: Version of Launch Template
        type: string
        default: $Default

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

run-name: ${{ github.event_name == 'workflow_dispatch' && format('{0} | GSRS_ENABLED={1}, GSRS_BRANCH={2}, LT_VERSION={3}', github.workflow, inputs.GSRS_ENABLED, inputs.GSRS_BRANCH, inputs.LT_VERSION) || '' }}
jobs:
  deploy:
    name: deploy to AWS
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: test
      url: https://precisionfda-test.dnanexus.com

    steps:
      - name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.ROLE_ARN }}

      - name: Set SSM Parameters
        run: |
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/chef/source_branch --value '${{ github.ref_name }}' --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/app/app_source/revision --value '${{ github.ref_name }}' --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/gsrs/revision --value '${{ inputs.GSRS_BRANCH }}' --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/app/environment/GSRS_ENABLED --value "$([[ "${{ inputs.GSRS_ENABLED }}" == "true" ]] && echo 1 || echo 0)" --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/chef/runlist --value '${{ inputs.CHEF_RUNLIST }}' --type String --overwrite >/dev/null
          aws ssm put-parameter --name /pfda/${{ vars.ENVIRONMENT }}/chef/attributes --value '${{ inputs.CHEF_ATTRIBUTES }}' --type String --overwrite >/dev/null

      - name: Run deploy.sh script
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          AWS_REGION: ${{ vars.REGION }}
          ENV_SUBNET1: ${{ vars.ENV_SUBNET1 }}
          ENV_SUBNET2: ${{ vars.ENV_SUBNET2 }}
          ENV_SUBNET3: ${{ vars.ENV_SUBNET3 }}
          ENV_ASG_NAME: ${{ vars.ENV_ASG_NAME }}
          ENV_TG: ${{ vars.ENV_TG }}
          ENV_LT_NAME: ${{ vars.ENV_LT_NAME }}
          ENV_LT_VERSION: ${{ inputs.LT_VERSION }}
          ENV_MIN_SIZE: ${{ vars.ENV_MIN_SIZE }}
          ENV_MAX_SIZE: ${{ vars.ENV_MAX_SIZE }}
          ENV_DESIRED_CAP: ${{ vars.ENV_DESIRED_CAP }}
        run: ./infra/deploy.sh
