export const NEWS_LIST_FETCH_START   = 'NEWS_LIST_FETCH_START'
export const NEWS_LIST_FETCH_SUCCESS = 'NEWS_LIST_FETCH_SUCCESS'
export const NEWS_LIST_FETCH_FAILURE = 'NEWS_LIST_FETCH_FAILURE'

export const NEWS_LIST_SET_PAGE = 'NEWS_LIST_SET_PAGE'
export const NEWS_LIST_SET_YEAR = 'NEWS_LIST_SET_YEAR'
export const NEWS_LIST_RESET_FILTERS = 'NEWS_LIST_RESET_FILTERS'

export const NEWS_YEAR_LIST_FETCH_START = 'NEWS_YEAR_LIST_FETCH_START'
export const NEWS_YEAR_LIST_FETCH_SUCCESS = 'NEWS_YEAR_LIST_FETCH_SUCCESS'
export const NEWS_YEAR_LIST_FETCH_FAILURE = 'NEWS_YEAR_LIST_FETCH_FAILURE'

export const NEWS_ITEM_FETCH_START    = 'NEWS_ITEM_FETCH_START'
export const NEWS_ITEM_FETCH_SUCCESS  = 'NEWS_ITEM_FETCH_SUCCESS'
export const NEWS_ITEM_FETCH_FAILURE  = 'NEWS_ITEM_FETCH_FAILURE'
